// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "convnextv2",
  models: [
    {
      model_id: "Xenova/convnextv2-large-22k-384",
      dtype: "quantized",
      architectures: ["ConvNextV2ForImageClassification"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Constant",
        "ConvInteger",
        "Div",
        "DynamicQuantizeLinear",
        "Erf",
        "MatMulInteger",
        "Mul",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Sqrt",
        "Sub",
        "Transpose",
      ],
    },
    {
      model_id: "Xenova/convnextv2-large-22k-384",
      dtype: "fp32",
      architectures: ["ConvNextV2ForImageClassification"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gemm",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Sqrt",
        "Sub",
        "Transpose",
      ],
    },
    {
      model_id:
        "onnx-internal-testing/tiny-random-ConvNextV2ForImageClassification-ONNX",
      dtype: "fp32",
      architectures: ["ConvNextV2ForImageClassification"],
      ops: [
        "Add",
        "Cast",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gemm",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceL2",
        "ReduceMean",
        "Sqrt",
        "Sub",
        "Transpose",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-ConvNextV2Model-ONNX",
      dtype: "fp32",
      architectures: ["ConvNextV2Model"],
      ops: [
        "Add",
        "Cast",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceL2",
        "ReduceMean",
        "Sqrt",
        "Sub",
        "Transpose",
      ],
    },
  ],
};
