// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "deberta-v2",
  models: [
    {
      model_id: "hf-internal-testing/tiny-random-DebertaV2ForQuestionAnswering",
      dtype: "fp32",
      architectures: ["DebertaV2ForQuestionAnswering"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Div",
        "Erf",
        "Gather",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id:
        "hf-internal-testing/tiny-random-DebertaV2ForSequenceClassification",
      dtype: "fp32",
      architectures: ["DebertaV2ForSequenceClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Div",
        "Erf",
        "Gather",
        "Gemm",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "hf-internal-testing/tiny-random-DebertaV2Model",
      dtype: "fp32",
      architectures: ["DebertaV2Model"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Div",
        "Erf",
        "Gather",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "mixedbread-ai/mxbai-rerank-base-v1",
      dtype: "quantized",
      architectures: ["DebertaV2ForSequenceClassification"],
      ops: [
        "Abs",
        "Add",
        "And",
        "Cast",
        "Ceil",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "GatherElements",
        "Greater",
        "Identity",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sign",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "mixedbread-ai/mxbai-rerank-base-v1",
      dtype: "fp32",
      architectures: ["DebertaV2ForSequenceClassification"],
      ops: [
        "Abs",
        "Add",
        "And",
        "Cast",
        "Ceil",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "GatherElements",
        "Gemm",
        "Greater",
        "Identity",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sign",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/camembertav2-base-fquad",
      dtype: "q4",
      architectures: ["DebertaV2ForQuestionAnswering"],
      ops: [
        "Abs",
        "Add",
        "And",
        "Cast",
        "Ceil",
        "Clip",
        "Concat",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "GatherElements",
        "Greater",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sign",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/camembertav2-base-fquad",
      dtype: "bnb4",
      architectures: ["DebertaV2ForQuestionAnswering"],
      ops: [
        "Abs",
        "Add",
        "And",
        "Cast",
        "Ceil",
        "Clip",
        "Concat",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "GatherElements",
        "Greater",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sign",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/camembertav2-base-fquad",
      dtype: "quantized",
      architectures: ["DebertaV2ForQuestionAnswering"],
      ops: [
        "Abs",
        "Add",
        "And",
        "Cast",
        "Ceil",
        "Clip",
        "Concat",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "GatherElements",
        "Greater",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sign",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/camembertav2-base-fquad",
      dtype: "fp32",
      architectures: ["DebertaV2ForQuestionAnswering"],
      ops: [
        "Abs",
        "Add",
        "And",
        "Cast",
        "Ceil",
        "Clip",
        "Concat",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "GatherElements",
        "Greater",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sign",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/deberta-small-long-nli",
      dtype: "q4",
      architectures: ["DebertaV2ForSequenceClassification"],
      ops: [
        "Abs",
        "Add",
        "And",
        "Cast",
        "Ceil",
        "Clip",
        "Concat",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "GatherElements",
        "Gemm",
        "Greater",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sign",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/deberta-small-long-nli",
      dtype: "bnb4",
      architectures: ["DebertaV2ForSequenceClassification"],
      ops: [
        "Abs",
        "Add",
        "And",
        "Cast",
        "Ceil",
        "Clip",
        "Concat",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "GatherElements",
        "Gemm",
        "Greater",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sign",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/deberta-small-long-nli",
      dtype: "quantized",
      architectures: ["DebertaV2ForSequenceClassification"],
      ops: [
        "Abs",
        "Add",
        "And",
        "Cast",
        "Ceil",
        "Clip",
        "Concat",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "GatherElements",
        "Greater",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sign",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/deberta-small-long-nli",
      dtype: "fp32",
      architectures: ["DebertaV2ForSequenceClassification"],
      ops: [
        "Abs",
        "Add",
        "And",
        "Cast",
        "Ceil",
        "Clip",
        "Concat",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "GatherElements",
        "Gemm",
        "Greater",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sign",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/deberta-v3-large",
      dtype: "q4",
      architectures: [],
      ops: [
        "Abs",
        "Add",
        "And",
        "Cast",
        "Ceil",
        "Clip",
        "Concat",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "GatherElements",
        "Greater",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sign",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/deberta-v3-large",
      dtype: "bnb4",
      architectures: [],
      ops: [
        "Abs",
        "Add",
        "And",
        "Cast",
        "Ceil",
        "Clip",
        "Concat",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "GatherElements",
        "Greater",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sign",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/deberta-v3-large",
      dtype: "fp32",
      architectures: [],
      ops: [
        "Abs",
        "Add",
        "And",
        "Cast",
        "Ceil",
        "Clip",
        "Concat",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "GatherElements",
        "Greater",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sign",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id:
        "onnx-internal-testing/tiny-random-DebertaV2ForQuestionAnswering-ONNX",
      dtype: "fp32",
      architectures: ["DebertaV2ForQuestionAnswering"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Div",
        "Erf",
        "Gather",
        "Identity",
        "MatMul",
        "Mul",
        "Not",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id:
        "onnx-internal-testing/tiny-random-DebertaV2ForSequenceClassification-ONNX",
      dtype: "fp32",
      architectures: ["DebertaV2ForSequenceClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Div",
        "Erf",
        "Gather",
        "Gemm",
        "Identity",
        "MatMul",
        "Mul",
        "Not",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-DebertaV2Model-ONNX",
      dtype: "fp32",
      architectures: ["DebertaV2Model"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Div",
        "Erf",
        "Gather",
        "Identity",
        "MatMul",
        "Mul",
        "Not",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
