// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "depth_anything",
  models: [
    {
      model_id: "Xenova/depth-anything-base-hf",
      dtype: "quantized",
      architectures: ["DepthAnythingForDepthEstimation"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "ConvInteger",
        "ConvTranspose",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/depth-anything-base-hf",
      dtype: "fp32",
      architectures: ["DepthAnythingForDepthEstimation"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "ConvTranspose",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/depth-anything-small-hf",
      dtype: "quantized",
      architectures: ["DepthAnythingForDepthEstimation"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "ConvInteger",
        "ConvTranspose",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Identity",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/depth-anything-small-hf",
      dtype: "fp32",
      architectures: ["DepthAnythingForDepthEstimation"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "ConvTranspose",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/depth-anything-v2-small",
      dtype: "q4",
      architectures: [],
      ops: [
        "Add",
        "Concat",
        "Conv",
        "ConvTranspose",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/depth-anything-v2-small",
      dtype: "bnb4",
      architectures: [],
      ops: [
        "Add",
        "Concat",
        "Conv",
        "ConvTranspose",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/depth-anything-v2-small",
      dtype: "q4f16",
      architectures: [],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Conv",
        "ConvTranspose",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/depth-anything-v2-small",
      dtype: "quantized",
      architectures: [],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConvInteger",
        "ConvTranspose",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/depth-anything-v2-small",
      dtype: "fp32",
      architectures: [],
      ops: [
        "Add",
        "Concat",
        "Conv",
        "ConvTranspose",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/depth-anything-v2-small",
      dtype: "fp16",
      architectures: [],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Conv",
        "ConvTranspose",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
