// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "detr",
  models: [
    {
      model_id: "Xenova/detr-resnet-50",
      dtype: "quantized",
      architectures: ["DetrForObjectDetection"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "ConvInteger",
        "Cos",
        "CumSum",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Expand",
        "Flatten",
        "Gather",
        "MatMul",
        "MatMulInteger",
        "MaxPool",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Sin",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/detr-resnet-50",
      dtype: "fp32",
      architectures: ["DetrForObjectDetection"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Cos",
        "CumSum",
        "Div",
        "Equal",
        "Expand",
        "Flatten",
        "Gather",
        "MatMul",
        "MaxPool",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Sin",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/detr-resnet-50-panoptic",
      dtype: "quantized",
      architectures: ["DetrForSegmentation"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "ConvInteger",
        "Cos",
        "CumSum",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Einsum",
        "Equal",
        "Expand",
        "Flatten",
        "Gather",
        "InstanceNormalization",
        "MatMul",
        "MatMulInteger",
        "MaxPool",
        "Mul",
        "Not",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Sin",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/detr-resnet-50-panoptic",
      dtype: "fp32",
      architectures: ["DetrForSegmentation"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Cos",
        "CumSum",
        "Div",
        "Einsum",
        "Equal",
        "Expand",
        "Flatten",
        "Gather",
        "InstanceNormalization",
        "MatMul",
        "MaxPool",
        "Mul",
        "Not",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Sin",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "hf-internal-testing/tiny-random-DetrForObjectDetection",
      dtype: "fp32",
      architectures: ["DetrForObjectDetection"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Cos",
        "CumSum",
        "Div",
        "Equal",
        "Expand",
        "Flatten",
        "Gather",
        "Identity",
        "MatMul",
        "MaxPool",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Sin",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-DetrModel-ONNX",
      dtype: "fp32",
      architectures: ["DetrModel"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Cos",
        "CumSum",
        "Div",
        "Equal",
        "Expand",
        "Flatten",
        "Gather",
        "Identity",
        "MatMul",
        "MaxPool",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
