// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "dpt",
  models: [
    {
      model_id: "Xenova/dpt-hybrid-midas",
      dtype: "quantized",
      architectures: ["DPTForDepthEstimation"],
      ops: [
        "Add",
        "BatchNormalization",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "ConvInteger",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Identity",
        "InstanceNormalization",
        "MatMul",
        "MatMulInteger",
        "MaxPool",
        "Mul",
        "Pad",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/dpt-hybrid-midas",
      dtype: "fp32",
      architectures: ["DPTForDepthEstimation"],
      ops: [
        "Add",
        "BatchNormalization",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Identity",
        "InstanceNormalization",
        "MatMul",
        "MaxPool",
        "Mul",
        "Pad",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/dpt-large",
      dtype: "quantized",
      architectures: ["DPTForDepthEstimation"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "ConvInteger",
        "ConvTranspose",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/dpt-large",
      dtype: "fp32",
      architectures: ["DPTForDepthEstimation"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "ConvTranspose",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "hf-internal-testing/tiny-random-DPTForDepthEstimation",
      dtype: "fp32",
      architectures: ["DPTForDepthEstimation"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "ConvTranspose",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/dpt-dinov2-small-kitti",
      dtype: "q4",
      architectures: ["DPTForDepthEstimation"],
      ops: [
        "Add",
        "Concat",
        "Conv",
        "ConvTranspose",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/dpt-dinov2-small-kitti",
      dtype: "bnb4",
      architectures: ["DPTForDepthEstimation"],
      ops: [
        "Add",
        "Concat",
        "Conv",
        "ConvTranspose",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/dpt-dinov2-small-kitti",
      dtype: "q4f16",
      architectures: ["DPTForDepthEstimation"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Conv",
        "ConvTranspose",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/dpt-dinov2-small-kitti",
      dtype: "quantized",
      architectures: ["DPTForDepthEstimation"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConvInteger",
        "ConvTranspose",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/dpt-dinov2-small-kitti",
      dtype: "fp32",
      architectures: ["DPTForDepthEstimation"],
      ops: [
        "Add",
        "Concat",
        "Conv",
        "ConvTranspose",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/dpt-dinov2-small-kitti",
      dtype: "fp16",
      architectures: ["DPTForDepthEstimation"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Conv",
        "ConvTranspose",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-DPTModel-ONNX",
      dtype: "fp32",
      architectures: ["DPTModel"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Resize",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
