// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "ernie_m",
  models: [
    {
      model_id: "Xenova/ernie-m-base-mnli-xnli",
      dtype: "q4",
      architectures: ["ErnieMForSequenceClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Erf",
        "Gather",
        "Gemm",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/ernie-m-base-mnli-xnli",
      dtype: "bnb4",
      architectures: ["ErnieMForSequenceClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Erf",
        "Gather",
        "Gemm",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/ernie-m-base-mnli-xnli",
      dtype: "quantized",
      architectures: ["ErnieMForSequenceClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Erf",
        "Gather",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/ernie-m-base-mnli-xnli",
      dtype: "fp32",
      architectures: ["ErnieMForSequenceClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Erf",
        "Gather",
        "Gemm",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/tiny-random-ErnieMForQuestionAnswering",
      dtype: "q4",
      architectures: ["ErnieMForQuestionAnswering"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Erf",
        "Gather",
        "Identity",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/tiny-random-ErnieMForQuestionAnswering",
      dtype: "bnb4",
      architectures: ["ErnieMForQuestionAnswering"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Erf",
        "Gather",
        "Identity",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/tiny-random-ErnieMForQuestionAnswering",
      dtype: "quantized",
      architectures: ["ErnieMForQuestionAnswering"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Erf",
        "Gather",
        "Identity",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/tiny-random-ErnieMForQuestionAnswering",
      dtype: "fp32",
      architectures: ["ErnieMForQuestionAnswering"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Erf",
        "Gather",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/tiny-random-ErnieMForSequenceClassification",
      dtype: "q4",
      architectures: ["ErnieMForSequenceClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Erf",
        "Gather",
        "Gemm",
        "Identity",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/tiny-random-ErnieMForSequenceClassification",
      dtype: "bnb4",
      architectures: ["ErnieMForSequenceClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Erf",
        "Gather",
        "Gemm",
        "Identity",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/tiny-random-ErnieMForSequenceClassification",
      dtype: "quantized",
      architectures: ["ErnieMForSequenceClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Erf",
        "Gather",
        "Identity",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/tiny-random-ErnieMForSequenceClassification",
      dtype: "fp32",
      architectures: ["ErnieMForSequenceClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Erf",
        "Gather",
        "Gemm",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/tiny-random-ErnieMForTokenClassification",
      dtype: "q4",
      architectures: ["ErnieMForTokenClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Erf",
        "Gather",
        "Identity",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/tiny-random-ErnieMForTokenClassification",
      dtype: "bnb4",
      architectures: ["ErnieMForTokenClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Erf",
        "Gather",
        "Identity",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/tiny-random-ErnieMForTokenClassification",
      dtype: "quantized",
      architectures: ["ErnieMForTokenClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Erf",
        "Gather",
        "Identity",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/tiny-random-ErnieMForTokenClassification",
      dtype: "fp32",
      architectures: ["ErnieMForTokenClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Erf",
        "Gather",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
  ],
};
