// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "esm",
  models: [
    {
      model_id: "Xenova/esm2_t30_150M_UR50D",
      dtype: "quantized",
      architectures: ["EsmForMaskedLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Cos",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Einsum",
        "Equal",
        "Erf",
        "Gather",
        "Identity",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/esm2_t30_150M_UR50D",
      dtype: "fp32",
      architectures: ["EsmForMaskedLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Cos",
        "Div",
        "Einsum",
        "Equal",
        "Erf",
        "Gather",
        "Identity",
        "MatMul",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/esm2_t6_8M_UR50D_sequence_classifier_v1",
      dtype: "quantized",
      architectures: ["EsmForSequenceClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Cos",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Einsum",
        "Equal",
        "Erf",
        "Gather",
        "Identity",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/esm2_t6_8M_UR50D_sequence_classifier_v1",
      dtype: "fp32",
      architectures: ["EsmForSequenceClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Cos",
        "Div",
        "Einsum",
        "Equal",
        "Erf",
        "Gather",
        "Gemm",
        "Identity",
        "MatMul",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/nucleotide-transformer-500m-1000g",
      dtype: "quantized",
      architectures: ["EsmForMaskedLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "CumSum",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Erf",
        "Gather",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Not",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/nucleotide-transformer-500m-1000g",
      dtype: "fp32",
      architectures: ["EsmForMaskedLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "CumSum",
        "Div",
        "Equal",
        "Erf",
        "Gather",
        "MatMul",
        "Mul",
        "Not",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-EsmForMaskedLM-ONNX",
      dtype: "fp32",
      architectures: ["EsmForMaskedLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "CumSum",
        "Div",
        "Equal",
        "Erf",
        "Gather",
        "Identity",
        "MatMul",
        "Mul",
        "Not",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
  ],
};
