// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "fastvit",
  models: [
    {
      model_id: "Xenova/fastvit_sa12.apple_in1k",
      dtype: "q4",
      architectures: [],
      ops: [
        "Add",
        "BatchNormalization",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Flatten",
        "Gather",
        "Gemm",
        "GlobalAveragePool",
        "Identity",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/fastvit_sa12.apple_in1k",
      dtype: "bnb4",
      architectures: [],
      ops: [
        "Add",
        "BatchNormalization",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Flatten",
        "Gather",
        "Gemm",
        "GlobalAveragePool",
        "Identity",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/fastvit_sa12.apple_in1k",
      dtype: "quantized",
      architectures: [],
      ops: [
        "Add",
        "BatchNormalization",
        "Cast",
        "Concat",
        "Constant",
        "ConvInteger",
        "Div",
        "DynamicQuantizeLinear",
        "Erf",
        "Flatten",
        "Gather",
        "GlobalAveragePool",
        "Identity",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/fastvit_sa12.apple_in1k",
      dtype: "fp32",
      architectures: [],
      ops: [
        "Add",
        "BatchNormalization",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Flatten",
        "Gather",
        "Gemm",
        "GlobalAveragePool",
        "Identity",
        "MatMul",
        "Mul",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/fastvit_t12.apple_in1k",
      dtype: "q4",
      architectures: [],
      ops: [
        "Add",
        "BatchNormalization",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Flatten",
        "Gemm",
        "GlobalAveragePool",
        "Identity",
        "Mul",
        "ReduceMean",
        "Relu",
        "Sigmoid",
        "Sub",
      ],
    },
    {
      model_id: "Xenova/fastvit_t12.apple_in1k",
      dtype: "quantized",
      architectures: [],
      ops: [
        "Add",
        "BatchNormalization",
        "Cast",
        "Constant",
        "ConvInteger",
        "Div",
        "DynamicQuantizeLinear",
        "Erf",
        "Flatten",
        "GlobalAveragePool",
        "Identity",
        "MatMulInteger",
        "Mul",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Sigmoid",
        "Sub",
      ],
    },
    {
      model_id: "Xenova/fastvit_t12.apple_in1k",
      dtype: "fp16",
      architectures: [],
      ops: [
        "Add",
        "BatchNormalization",
        "Cast",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Flatten",
        "Gemm",
        "GlobalAveragePool",
        "Identity",
        "Mul",
        "ReduceMean",
        "Relu",
        "Sigmoid",
        "Sub",
      ],
    },
  ],
};
