// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "gemma2",
  models: [
    {
      model_id: "hf-internal-testing/tiny-random-Gemma2ForCausalLM",
      dtype: "fp32",
      architectures: ["Gemma2ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Cos",
        "Div",
        "Equal",
        "Expand",
        "Gather",
        "Greater",
        "Identity",
        "MatMul",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "ScatterND",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Sqrt",
        "Tanh",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/gemma-2-2b-jpn-it",
      dtype: "q4f16",
      architectures: ["Gemma2ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Equal",
        "Expand",
        "FastGelu",
        "Gather",
        "Less",
        "MatMulNBits",
        "Mul",
        "MultiHeadAttention",
        "Range",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Slice",
        "Squeeze",
        "Sub",
        "Tanh",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
