// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "ibert",
  models: [
    {
      model_id: "onnx-internal-testing/tiny-random-IBertForMaskedLM-ONNX",
      dtype: "fp32",
      architectures: ["IBertForMaskedLM"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Equal",
        "Erf",
        "Floor",
        "Gather",
        "Identity",
        "MatMul",
        "Max",
        "Min",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "Reciprocal",
        "ReduceMax",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Round",
        "Shape",
        "Sign",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-IBertForMultipleChoice-ONNX",
      dtype: "fp32",
      architectures: ["IBertForMultipleChoice"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Equal",
        "Floor",
        "Gather",
        "Gemm",
        "Identity",
        "MatMul",
        "Max",
        "Min",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "Reciprocal",
        "ReduceMax",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Round",
        "Shape",
        "Sign",
        "Slice",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id:
        "onnx-internal-testing/tiny-random-IBertForQuestionAnswering-ONNX",
      dtype: "fp32",
      architectures: ["IBertForQuestionAnswering"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Equal",
        "Floor",
        "Gather",
        "Identity",
        "MatMul",
        "Max",
        "Min",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "Reciprocal",
        "ReduceMax",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Round",
        "Shape",
        "Sign",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id:
        "onnx-internal-testing/tiny-random-IBertForSequenceClassification-ONNX",
      dtype: "fp32",
      architectures: ["IBertForSequenceClassification"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Equal",
        "Floor",
        "Gather",
        "Gemm",
        "Identity",
        "MatMul",
        "Max",
        "Min",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "Reciprocal",
        "ReduceMax",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Round",
        "Shape",
        "Sign",
        "Sqrt",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-IBertModel-ONNX",
      dtype: "fp32",
      architectures: ["IBertModel"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Equal",
        "Floor",
        "Gather",
        "Identity",
        "MatMul",
        "Max",
        "Min",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "Reciprocal",
        "ReduceMax",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Round",
        "Shape",
        "Sign",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
  ],
};
