// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "idefics3",
  models: [
    {
      model_id:
        "hf-internal-testing/tiny-random-Idefics3ForConditionalGeneration",
      dtype: "fp32",
      architectures: ["Idefics3ForConditionalGeneration"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Equal",
        "Expand",
        "Flatten",
        "Gather",
        "GatherND",
        "Greater",
        "GroupQueryAttention",
        "Less",
        "MatMul",
        "Mul",
        "NonZero",
        "Not",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
