// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "ijepa",
  models: [
    {
      model_id: "onnx-community/ijepa_vith14_22k",
      dtype: "q4",
      architectures: ["IJepaModel"],
      ops: [
        "Add",
        "Conv",
        "Div",
        "Erf",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
      ],
    },
    {
      model_id: "onnx-community/ijepa_vith14_22k",
      dtype: "bnb4",
      architectures: ["IJepaModel"],
      ops: [
        "Add",
        "Conv",
        "Div",
        "Erf",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
      ],
    },
    {
      model_id: "onnx-community/ijepa_vith14_22k",
      dtype: "q4f16",
      architectures: ["IJepaModel"],
      ops: [
        "Add",
        "Cast",
        "Conv",
        "Div",
        "Erf",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
      ],
    },
    {
      model_id: "onnx-community/ijepa_vith14_22k",
      dtype: "quantized",
      architectures: ["IJepaModel"],
      ops: [
        "Add",
        "Cast",
        "ConvInteger",
        "Div",
        "DynamicQuantizeLinear",
        "Erf",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
      ],
    },
    {
      model_id: "onnx-community/ijepa_vith14_22k",
      dtype: "fp32",
      architectures: ["IJepaModel"],
      ops: [
        "Add",
        "Conv",
        "Div",
        "Erf",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
      ],
    },
    {
      model_id: "onnx-community/ijepa_vith14_22k",
      dtype: "fp16",
      architectures: ["IJepaModel"],
      ops: [
        "Add",
        "Cast",
        "Conv",
        "Div",
        "Erf",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
      ],
    },
  ],
};
