// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "jina_clip",
  models: [
    {
      model_id: "jinaai/jina-clip-v1",
      dtype: "uint8",
      architectures: ["JinaCLIPModel"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "ConvInteger",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Einsum",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "jinaai/jina-clip-v1",
      dtype: "fp32",
      architectures: ["JinaCLIPModel"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Einsum",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "Range",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "jinaai/jina-clip-v1",
      dtype: "bnb4",
      architectures: ["JinaCLIPModel"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Einsum",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "jinaai/jina-clip-v1",
      dtype: "q4",
      architectures: ["JinaCLIPModel"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Einsum",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "jinaai/jina-clip-v2",
      dtype: "q4",
      architectures: ["JinaCLIPModel"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Einsum",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "ReduceL2",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "jinaai/jina-clip-v2",
      dtype: "bnb4",
      architectures: ["JinaCLIPModel"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Einsum",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "ReduceL2",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "jinaai/jina-clip-v2",
      dtype: "quantized",
      architectures: ["JinaCLIPModel"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "ConvInteger",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Einsum",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "ReduceL2",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "jinaai/jina-clip-v2",
      dtype: "fp32",
      architectures: ["JinaCLIPModel"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Einsum",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "ReduceL2",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
