// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "llava_onevision",
  models: [
    {
      model_id: "llava-hf/llava-onevision-qwen2-0.5b-ov-hf",
      dtype: "fp16",
      architectures: ["LlavaOnevisionForConditionalGeneration"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Greater",
        "MatMul",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "llava-hf/llava-onevision-qwen2-0.5b-ov-hf",
      dtype: "int8",
      architectures: ["LlavaOnevisionForConditionalGeneration"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "ConvInteger",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Greater",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "llava-hf/llava-onevision-qwen2-0.5b-ov-hf",
      dtype: "bnb4",
      architectures: ["LlavaOnevisionForConditionalGeneration"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Greater",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "llava-hf/llava-onevision-qwen2-0.5b-ov-hf",
      dtype: "q4f16",
      architectures: ["LlavaOnevisionForConditionalGeneration"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Greater",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
