// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "modnet",
  models: [
    {
      model_id: "Xenova/modnet",
      dtype: "quantized",
      architectures: [],
      ops: [
        "Add",
        "BatchNormalization",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "ConvInteger",
        "DynamicQuantizeLinear",
        "Expand",
        "Gather",
        "GlobalAveragePool",
        "InstanceNormalization",
        "MatMulInteger",
        "Mul",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Slice",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/modnet",
      dtype: "fp32",
      architectures: [],
      ops: [
        "Add",
        "BatchNormalization",
        "Clip",
        "Concat",
        "Constant",
        "Conv",
        "Expand",
        "Gather",
        "GlobalAveragePool",
        "InstanceNormalization",
        "MatMul",
        "Mul",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Slice",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/modnet",
      dtype: "fp16",
      architectures: [],
      ops: [
        "Add",
        "BatchNormalization",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "Conv",
        "Expand",
        "Gather",
        "GlobalAveragePool",
        "InstanceNormalization",
        "MatMul",
        "Mul",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Slice",
        "Unsqueeze",
      ],
    },
  ],
};
