// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "mpnet",
  models: [
    {
      model_id: "Xenova/multi-qa-mpnet-base-dot-v1",
      dtype: "quantized",
      architectures: ["MPNetForMaskedLM"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Less",
        "Log",
        "MatMul",
        "MatMulInteger",
        "Min",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/multi-qa-mpnet-base-dot-v1",
      dtype: "fp32",
      architectures: ["MPNetForMaskedLM"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Less",
        "Log",
        "MatMul",
        "Min",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-MPNetForMultipleChoice-ONNX",
      dtype: "fp32",
      architectures: ["MPNetForMultipleChoice"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Gemm",
        "Identity",
        "Less",
        "Log",
        "MatMul",
        "Min",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id:
        "onnx-internal-testing/tiny-random-MPNetForQuestionAnswering-ONNX",
      dtype: "fp32",
      architectures: ["MPNetForQuestionAnswering"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Identity",
        "Less",
        "Log",
        "MatMul",
        "Min",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id:
        "onnx-internal-testing/tiny-random-MPNetForSequenceClassification-ONNX",
      dtype: "fp32",
      architectures: ["MPNetForSequenceClassification"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Gemm",
        "Identity",
        "Less",
        "Log",
        "MatMul",
        "Min",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-MPNetModel-ONNX",
      dtype: "fp32",
      architectures: ["MPNetModel"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Identity",
        "Less",
        "Log",
        "MatMul",
        "Min",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
