// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "phi",
  models: [
    {
      model_id: "Xenova/phi-1_5_dev",
      dtype: "quantized",
      architectures: ["PhiForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Expand",
        "Gather",
        "Less",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/phi-1_5_dev",
      dtype: "fp32",
      architectures: ["PhiForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Equal",
        "Expand",
        "Gather",
        "Less",
        "MatMul",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/tiny-random-PhiForCausalLM",
      dtype: "quantized",
      architectures: ["PhiForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Identity",
        "Less",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/tiny-random-PhiForCausalLM",
      dtype: "fp32",
      architectures: ["PhiForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Identity",
        "Less",
        "MatMul",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/moondream2.text_model-ONNX",
      dtype: "q4",
      architectures: ["PhiForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "FastGelu",
        "Gather",
        "GroupQueryAttention",
        "LayerNormalization",
        "MatMulNBits",
        "ReduceSum",
        "Shape",
        "SkipLayerNormalization",
        "Sub",
      ],
    },
    {
      model_id: "onnx-community/moondream2.text_model-ONNX",
      dtype: "bnb4",
      architectures: ["PhiForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "Equal",
        "Expand",
        "FastGelu",
        "Gather",
        "LayerNormalization",
        "Less",
        "MatMulBnb4",
        "MultiHeadAttention",
        "Range",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "SkipLayerNormalization",
        "Slice",
        "Squeeze",
        "Sub",
        "Tile",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/moondream2.text_model-ONNX",
      dtype: "q4f16",
      architectures: ["PhiForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "Equal",
        "Expand",
        "FastGelu",
        "Gather",
        "LayerNormalization",
        "Less",
        "MatMulNBits",
        "MultiHeadAttention",
        "Range",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "SkipLayerNormalization",
        "Slice",
        "Squeeze",
        "Sub",
        "Tile",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/moondream2.text_model-ONNX",
      dtype: "quantized",
      architectures: ["PhiForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "DequantizeLinear",
        "DynamicQuantizeLinear",
        "Equal",
        "Expand",
        "FastGelu",
        "Gather",
        "LayerNormalization",
        "Less",
        "MatMulInteger",
        "Mul",
        "MultiHeadAttention",
        "Range",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "SkipLayerNormalization",
        "Slice",
        "Squeeze",
        "Sub",
        "Tile",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/moondream2.text_model-ONNX",
      dtype: "fp32",
      architectures: ["PhiForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "Equal",
        "Expand",
        "FastGelu",
        "Gather",
        "LayerNormalization",
        "Less",
        "MatMul",
        "MultiHeadAttention",
        "Range",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "SkipLayerNormalization",
        "Slice",
        "Squeeze",
        "Sub",
        "Tile",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-PhiForCausalLM-ONNX",
      dtype: "fp32",
      architectures: ["PhiForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Cos",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Greater",
        "Identity",
        "MatMul",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "ScatterND",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id:
        "onnx-internal-testing/tiny-random-PhiForSequenceClassification-ONNX",
      dtype: "fp32",
      architectures: ["PhiForSequenceClassification"],
      ops: [
        "Add",
        "ArgMax",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Cos",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Flatten",
        "Gather",
        "Greater",
        "Identity",
        "MatMul",
        "Mod",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "ScatterND",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
