// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "phi3_v",
  models: [
    {
      model_id: "onnx-community/Phi-3-vision-128k-instruct",
      dtype: "q4f16",
      architectures: ["Phi3VForCausalLM"],
      ops: [
        "Add",
        "And",
        "Attention",
        "BiasGelu",
        "Cast",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Equal",
        "Expand",
        "Gather",
        "Greater",
        "GreaterOrEqual",
        "GroupQueryAttention",
        "Identity",
        "If",
        "LayerNormalization",
        "Less",
        "Loop",
        "MatMulNBits",
        "Mul",
        "NonZero",
        "Pow",
        "QuickGelu",
        "ReduceMax",
        "ReduceMin",
        "ReduceProd",
        "ReduceSum",
        "Reshape",
        "RotaryEmbedding",
        "ScatterND",
        "SequenceAt",
        "SequenceConstruct",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Slice",
        "SplitToSequence",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/Phi-3.5-vision-instruct",
      dtype: "q4f16",
      architectures: ["Phi3VForCausalLM"],
      ops: [
        "Add",
        "And",
        "BiasGelu",
        "Cast",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Equal",
        "Expand",
        "Gather",
        "Greater",
        "GreaterOrEqual",
        "GroupQueryAttention",
        "Identity",
        "If",
        "LayerNormalization",
        "Less",
        "Loop",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "NonZero",
        "Pow",
        "QuickGelu",
        "ReduceMax",
        "ReduceMin",
        "ReduceProd",
        "ReduceSum",
        "Reshape",
        "RotaryEmbedding",
        "ScatterND",
        "SequenceAt",
        "SequenceConstruct",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Slice",
        "Softmax",
        "SplitToSequence",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/Phi-3.5-vision-instruct",
      dtype: "q4",
      architectures: ["Phi3VForCausalLM"],
      ops: [
        "Add",
        "And",
        "Attention",
        "BiasGelu",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Equal",
        "Expand",
        "Gather",
        "Greater",
        "GroupQueryAttention",
        "Identity",
        "If",
        "LayerNormalization",
        "Less",
        "Loop",
        "MatMulNBits",
        "Mul",
        "NonZero",
        "Pow",
        "QuickGelu",
        "ReduceMin",
        "ReduceProd",
        "ReduceSum",
        "Reshape",
        "ScatterND",
        "SequenceAt",
        "SequenceConstruct",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Slice",
        "SplitToSequence",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
