// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "pyannote",
  models: [
    {
      model_id: "onnx-community/pyannote-segmentation-3.0",
      dtype: "q4",
      architectures: [],
      ops: [
        "Abs",
        "Add",
        "Concat",
        "ConstantOfShape",
        "Conv",
        "Equal",
        "Gather",
        "If",
        "InstanceNormalization",
        "LSTM",
        "LeakyRelu",
        "LogSoftmax",
        "MatMulNBits",
        "MaxPool",
        "Reshape",
        "Shape",
        "Slice",
        "Squeeze",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/pyannote-segmentation-3.0",
      dtype: "bnb4",
      architectures: [],
      ops: [
        "Abs",
        "Add",
        "Concat",
        "ConstantOfShape",
        "Conv",
        "Equal",
        "Gather",
        "If",
        "InstanceNormalization",
        "LSTM",
        "LeakyRelu",
        "LogSoftmax",
        "MatMulBnb4",
        "MaxPool",
        "Reshape",
        "Shape",
        "Slice",
        "Squeeze",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/pyannote-segmentation-3.0",
      dtype: "q4f16",
      architectures: [],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "Conv",
        "Equal",
        "Gather",
        "If",
        "InstanceNormalization",
        "LSTM",
        "LeakyRelu",
        "LogSoftmax",
        "MatMulNBits",
        "MaxPool",
        "Reshape",
        "Shape",
        "Slice",
        "Squeeze",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/pyannote-segmentation-3.0",
      dtype: "quantized",
      architectures: [],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "ConvInteger",
        "DynamicQuantizeLSTM",
        "DynamicQuantizeLinear",
        "Equal",
        "Gather",
        "If",
        "InstanceNormalization",
        "LeakyRelu",
        "LogSoftmax",
        "MatMulInteger",
        "MaxPool",
        "Mul",
        "Reshape",
        "Shape",
        "Slice",
        "Squeeze",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/pyannote-segmentation-3.0",
      dtype: "fp32",
      architectures: [],
      ops: [
        "Abs",
        "Add",
        "Concat",
        "ConstantOfShape",
        "Conv",
        "Equal",
        "Gather",
        "If",
        "InstanceNormalization",
        "LSTM",
        "LeakyRelu",
        "LogSoftmax",
        "MatMul",
        "MaxPool",
        "Reshape",
        "Shape",
        "Slice",
        "Squeeze",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/pyannote-segmentation-3.0",
      dtype: "fp16",
      architectures: [],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "Conv",
        "Equal",
        "Gather",
        "If",
        "InstanceNormalization",
        "LSTM",
        "LeakyRelu",
        "LogSoftmax",
        "MatMul",
        "MaxPool",
        "Reshape",
        "Shape",
        "Slice",
        "Squeeze",
        "Transpose",
        "Unsqueeze",
      ],
    },
  ],
};
