// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "qwen2",
  models: [
    {
      model_id: "Xenova/Qwen1.5-0.5B-Chat",
      dtype: "quantized",
      architectures: ["Qwen2ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Expand",
        "Gather",
        "Less",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/Qwen1.5-0.5B-Chat",
      dtype: "fp32",
      architectures: ["Qwen2ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Equal",
        "Expand",
        "Gather",
        "Less",
        "MatMul",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/DeepSeek-R1-Distill-Qwen-1.5B-ONNX",
      dtype: "q4",
      architectures: ["Qwen2ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "Equal",
        "Expand",
        "Gather",
        "Less",
        "MatMulNBits",
        "Mul",
        "MultiHeadAttention",
        "Range",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Slice",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/DeepSeek-R1-Distill-Qwen-1.5B-ONNX",
      dtype: "bnb4",
      architectures: ["Qwen2ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "Equal",
        "Expand",
        "Gather",
        "Less",
        "MatMulBnb4",
        "Mul",
        "MultiHeadAttention",
        "Range",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Slice",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/DeepSeek-R1-Distill-Qwen-1.5B-ONNX",
      dtype: "quantized",
      architectures: ["Qwen2ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "DequantizeLinear",
        "DynamicQuantizeLinear",
        "Equal",
        "Expand",
        "Gather",
        "Less",
        "MatMulInteger",
        "Mul",
        "MultiHeadAttention",
        "Range",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Slice",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/DeepSeek-R1-Distill-Qwen-1.5B-ONNX",
      dtype: "fp32",
      architectures: ["Qwen2ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "Equal",
        "Expand",
        "Gather",
        "Less",
        "MatMul",
        "Mul",
        "MultiHeadAttention",
        "Range",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Slice",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/OuteTTS-0.2-500M",
      dtype: "q4",
      architectures: ["Qwen2ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "Equal",
        "Expand",
        "Gather",
        "Less",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "MultiHeadAttention",
        "Range",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Slice",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/OuteTTS-0.2-500M",
      dtype: "bnb4",
      architectures: ["Qwen2ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "Equal",
        "Expand",
        "Gather",
        "Less",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "MultiHeadAttention",
        "Range",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Slice",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/OuteTTS-0.2-500M",
      dtype: "quantized",
      architectures: ["Qwen2ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "DequantizeLinear",
        "DynamicQuantizeLinear",
        "Equal",
        "Expand",
        "Gather",
        "Less",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "MultiHeadAttention",
        "Range",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Slice",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/Qwen2.5-0.5B-Instruct",
      dtype: "q4",
      architectures: ["Qwen2ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "Div",
        "Equal",
        "Expand",
        "Gather",
        "Greater",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/Qwen2.5-0.5B-Instruct",
      dtype: "bnb4",
      architectures: ["Qwen2ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "Div",
        "Equal",
        "Expand",
        "Gather",
        "Greater",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/Qwen2.5-0.5B-Instruct",
      dtype: "quantized",
      architectures: ["Qwen2ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Expand",
        "Gather",
        "Greater",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/Qwen2.5-0.5B-Instruct",
      dtype: "fp32",
      architectures: ["Qwen2ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "Div",
        "Equal",
        "Expand",
        "Gather",
        "Greater",
        "MatMul",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/Qwen2.5-0.5B-Instruct-ONNX-GQA",
      dtype: "q4",
      architectures: ["Qwen2ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Gather",
        "GroupQueryAttention",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "ReduceSum",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Sub",
        "Transpose",
      ],
    },
    {
      model_id: "onnx-community/Qwen2.5-0.5B-Instruct-ONNX-GQA",
      dtype: "bnb4",
      architectures: ["Qwen2ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Gather",
        "GroupQueryAttention",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "ReduceSum",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Sub",
        "Transpose",
      ],
    },
    {
      model_id: "onnx-community/Qwen2.5-0.5B-Instruct-ONNX-GQA",
      dtype: "quantized",
      architectures: ["Qwen2ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "DequantizeLinear",
        "DynamicQuantizeLinear",
        "Gather",
        "GroupQueryAttention",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "ReduceSum",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Sub",
        "Transpose",
      ],
    },
    {
      model_id: "onnx-community/Qwen2.5-0.5B-Instruct-ONNX-GQA",
      dtype: "fp32",
      architectures: ["Qwen2ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Gather",
        "GroupQueryAttention",
        "MatMul",
        "Mul",
        "ReduceSum",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Sub",
        "Transpose",
      ],
    },
    {
      model_id: "onnx-community/Qwen2.5-Coder-0.5B-Instruct",
      dtype: "q4",
      architectures: ["Qwen2ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Gather",
        "GroupQueryAttention",
        "MatMulNBits",
        "Mul",
        "ReduceSum",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Sub",
      ],
    },
    {
      model_id: "onnx-community/SmallThinker-3B-Preview-DML-ONNX",
      dtype: "q4f16",
      architectures: ["Qwen2ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Gather",
        "GroupQueryAttention",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "ReduceSum",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/SmallThinker-3B-Preview-DML-ONNX",
      dtype: "fp16",
      architectures: ["Qwen2ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Gather",
        "GroupQueryAttention",
        "MatMul",
        "Mul",
        "ReduceSum",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/ZR1-1.5B-ONNX",
      dtype: "q4",
      architectures: ["Qwen2ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Gather",
        "GroupQueryAttention",
        "MatMulNBits",
        "Mul",
        "ReduceSum",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Sub",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/ZR1-1.5B-ONNX",
      dtype: "bnb4",
      architectures: ["Qwen2ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Gather",
        "GroupQueryAttention",
        "MatMulBnb4",
        "Mul",
        "ReduceSum",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Sub",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/ZR1-1.5B-ONNX",
      dtype: "quantized",
      architectures: ["Qwen2ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "DequantizeLinear",
        "DynamicQuantizeLinear",
        "Gather",
        "GroupQueryAttention",
        "MatMulInteger",
        "Mul",
        "ReduceSum",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Sub",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/ZR1-1.5B-ONNX",
      dtype: "fp32",
      architectures: ["Qwen2ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Gather",
        "GroupQueryAttention",
        "MatMul",
        "Mul",
        "ReduceSum",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Sub",
        "Unsqueeze",
      ],
    },
  ],
};
