// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "qwen3",
  models: [
    {
      model_id: "onnx-community/Qwen3-0.6B-ONNX",
      dtype: "q4",
      architectures: ["Qwen3ForCausalLM"],
      ops: [
        "Cast",
        "Concat",
        "Constant",
        "Gather",
        "GroupQueryAttention",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "ReduceSum",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/Qwen3-0.6B-ONNX",
      dtype: "bnb4",
      architectures: ["Qwen3ForCausalLM"],
      ops: [
        "Cast",
        "Concat",
        "Constant",
        "Gather",
        "GroupQueryAttention",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "ReduceSum",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/Qwen3-0.6B-ONNX",
      dtype: "quantized",
      architectures: ["Qwen3ForCausalLM"],
      ops: [
        "Cast",
        "Concat",
        "Constant",
        "DequantizeLinear",
        "DynamicQuantizeLinear",
        "Gather",
        "GroupQueryAttention",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "ReduceSum",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/Qwen3-0.6B-ONNX",
      dtype: "fp32",
      architectures: ["Qwen3ForCausalLM"],
      ops: [
        "Cast",
        "Concat",
        "Constant",
        "Gather",
        "GroupQueryAttention",
        "MatMul",
        "Mul",
        "ReduceSum",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
  ],
};
