// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "sam",
  models: [
    {
      model_id: "Xenova/sam-vit-huge",
      dtype: "fp16",
      architectures: ["SamModel"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "ConvTranspose",
        "Cos",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "Mul",
        "Neg",
        "Not",
        "OneHot",
        "Pow",
        "Range",
        "ReduceMean",
        "Relu",
        "Reshape",
        "ScatterND",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/slimsam-77-uniform",
      dtype: "fp16",
      architectures: ["SamModel"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "ConvTranspose",
        "Cos",
        "Div",
        "Einsum",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Identity",
        "MatMul",
        "Mod",
        "Mul",
        "Neg",
        "Not",
        "OneHot",
        "Pad",
        "Pow",
        "Range",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "ScatterND",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/slimsam-77-uniform",
      dtype: "quantized",
      architectures: ["SamModel"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "ConvInteger",
        "ConvTranspose",
        "Cos",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Einsum",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Identity",
        "MatMul",
        "MatMulInteger",
        "Mod",
        "Mul",
        "Neg",
        "Not",
        "OneHot",
        "Pad",
        "Pow",
        "Range",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "ScatterND",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
