// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "sapiens",
  models: [
    {
      model_id: "onnx-community/sapiens-seg-0.3b",
      dtype: "q4",
      architectures: [],
      ops: [
        "Add",
        "Conv",
        "ConvTranspose",
        "Div",
        "Erf",
        "Gather",
        "InstanceNormalization",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Sigmoid",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
      ],
    },
    {
      model_id: "onnx-community/sapiens-seg-0.3b",
      dtype: "bnb4",
      architectures: [],
      ops: [
        "Add",
        "Conv",
        "ConvTranspose",
        "Div",
        "Erf",
        "Gather",
        "InstanceNormalization",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Sigmoid",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
      ],
    },
    {
      model_id: "onnx-community/sapiens-seg-0.3b",
      dtype: "q4f16",
      architectures: [],
      ops: [
        "Add",
        "Cast",
        "Conv",
        "ConvTranspose",
        "Div",
        "Erf",
        "Gather",
        "InstanceNormalization",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Sigmoid",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
      ],
    },
    {
      model_id: "onnx-community/sapiens-seg-0.3b",
      dtype: "quantized",
      architectures: [],
      ops: [
        "Add",
        "Cast",
        "ConvInteger",
        "ConvTranspose",
        "Div",
        "DynamicQuantizeLinear",
        "Erf",
        "Gather",
        "InstanceNormalization",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Sigmoid",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
      ],
    },
    {
      model_id: "onnx-community/sapiens-seg-0.3b",
      dtype: "fp32",
      architectures: [],
      ops: [
        "Add",
        "Conv",
        "ConvTranspose",
        "Div",
        "Erf",
        "Gather",
        "InstanceNormalization",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Sigmoid",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
      ],
    },
    {
      model_id: "onnx-community/sapiens-seg-0.3b",
      dtype: "fp16",
      architectures: [],
      ops: [
        "Add",
        "Cast",
        "Conv",
        "ConvTranspose",
        "Div",
        "Erf",
        "Gather",
        "InstanceNormalization",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Sigmoid",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
      ],
    },
  ],
};
