// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "sew",
  models: [
    {
      model_id:
        "onnx-internal-testing/tiny-random-SEWForSequenceClassification-ONNX",
      dtype: "fp32",
      architectures: ["SEWForSequenceClassification"],
      ops: [
        "Add",
        "AveragePool",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "Gemm",
        "Identity",
        "InstanceNormalization",
        "MatMul",
        "Mul",
        "Pad",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-SEWModel-ONNX",
      dtype: "fp32",
      architectures: ["SEWModel"],
      ops: [
        "Add",
        "AveragePool",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "Identity",
        "InstanceNormalization",
        "MatMul",
        "Mul",
        "Pad",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
  ],
};
