// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "squeezebert",
  models: [
    {
      model_id: "Xenova/squeezebert-mnli",
      dtype: "quantized",
      architectures: [],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConvInteger",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Erf",
        "Gather",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/squeezebert-mnli",
      dtype: "fp32",
      architectures: [],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/squeezebert-uncased",
      dtype: "quantized",
      architectures: [],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConvInteger",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Erf",
        "Gather",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/squeezebert-uncased",
      dtype: "fp32",
      architectures: [],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id:
        "onnx-internal-testing/tiny-random-SqueezeBertForMultipleChoice-ONNX",
      dtype: "fp32",
      architectures: ["SqueezeBertForMultipleChoice"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "Gemm",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id:
        "onnx-internal-testing/tiny-random-SqueezeBertForQuestionAnswering-ONNX",
      dtype: "fp32",
      architectures: ["SqueezeBertForQuestionAnswering"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id:
        "onnx-internal-testing/tiny-random-SqueezeBertForSequenceClassification-ONNX",
      dtype: "fp32",
      architectures: ["SqueezeBertForSequenceClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "Gemm",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
      ],
    },
  ],
};
