// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "unispeech-sat",
  models: [
    {
      model_id: "Xenova/unispeech-sat-base-100h-libri-ft",
      dtype: "quantized",
      architectures: ["UniSpeechSatForCTC"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConvInteger",
        "Div",
        "DynamicQuantizeLinear",
        "Erf",
        "Gather",
        "InstanceNormalization",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/unispeech-sat-base-100h-libri-ft",
      dtype: "fp32",
      architectures: ["UniSpeechSatForCTC"],
      ops: [
        "Add",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "InstanceNormalization",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/unispeech-sat-base-100h-libri-ft",
      dtype: "fp16",
      architectures: ["UniSpeechSatForCTC"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "InstanceNormalization",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/unispeech-sat-base-plus-sd",
      dtype: "quantized",
      architectures: ["UniSpeechSatForAudioFrameClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConvInteger",
        "Div",
        "DynamicQuantizeLinear",
        "Erf",
        "Gather",
        "InstanceNormalization",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/unispeech-sat-base-plus-sd",
      dtype: "fp32",
      architectures: ["UniSpeechSatForAudioFrameClassification"],
      ops: [
        "Add",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "InstanceNormalization",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/unispeech-sat-base-plus-sv",
      dtype: "quantized",
      architectures: ["UniSpeechSatForXVector"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConvInteger",
        "Div",
        "DynamicQuantizeLinear",
        "Erf",
        "Gather",
        "InstanceNormalization",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pad",
        "Pow",
        "Range",
        "ReduceMean",
        "ReduceProd",
        "ReduceSum",
        "Relu",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/unispeech-sat-base-plus-sv",
      dtype: "fp32",
      architectures: ["UniSpeechSatForXVector"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "Gemm",
        "InstanceNormalization",
        "MatMul",
        "Mul",
        "Pad",
        "Pow",
        "Range",
        "ReduceMean",
        "ReduceProd",
        "ReduceSum",
        "Relu",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/unispeech-sat-large-sv",
      dtype: "quantized",
      architectures: ["UniSpeechSatForXVector"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConvInteger",
        "Div",
        "DynamicQuantizeLinear",
        "Erf",
        "Gather",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pad",
        "Pow",
        "Range",
        "ReduceMean",
        "ReduceProd",
        "ReduceSum",
        "Relu",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/unispeech-sat-large-sv",
      dtype: "fp32",
      architectures: ["UniSpeechSatForXVector"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "Gemm",
        "MatMul",
        "Mul",
        "Pad",
        "Pow",
        "Range",
        "ReduceMean",
        "ReduceProd",
        "ReduceSum",
        "Relu",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id:
        "onnx-internal-testing/tiny-random-UniSpeechSatForSequenceClassification-ONNX",
      dtype: "fp32",
      architectures: ["UniSpeechSatForSequenceClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "Gemm",
        "Identity",
        "InstanceNormalization",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-UniSpeechSatForXVector-ONNX",
      dtype: "fp32",
      architectures: ["UniSpeechSatForXVector"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "Gemm",
        "Identity",
        "InstanceNormalization",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "ReduceProd",
        "Relu",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-UniSpeechSatModel-ONNX",
      dtype: "fp32",
      architectures: ["UniSpeechSatModel"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "Identity",
        "InstanceNormalization",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
  ],
};
