// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "unknown",
  models: [
    {
      model_id: "jinaai/jina-reranker-v2-base-multilingual",
      dtype: "q4",
      architectures: ["XLMRobertaForSequenceClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Einsum",
        "Equal",
        "Erf",
        "Gather",
        "Gemm",
        "MatMulNBits",
        "Mul",
        "Not",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "jinaai/jina-reranker-v2-base-multilingual",
      dtype: "bnb4",
      architectures: ["XLMRobertaForSequenceClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Einsum",
        "Equal",
        "Erf",
        "Gather",
        "Gemm",
        "MatMulBnb4",
        "Mul",
        "Not",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "jinaai/jina-reranker-v2-base-multilingual",
      dtype: "quantized",
      architectures: ["XLMRobertaForSequenceClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "CumSum",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Einsum",
        "Equal",
        "Erf",
        "Gather",
        "MatMulInteger",
        "Mul",
        "Not",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "jinaai/jina-reranker-v2-base-multilingual",
      dtype: "fp32",
      architectures: ["XLMRobertaForSequenceClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Einsum",
        "Equal",
        "Erf",
        "Gather",
        "Gemm",
        "MatMul",
        "Mul",
        "Not",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/GLiNER_ITA_LARGE",
      dtype: "q4",
      architectures: [],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Einsum",
        "Equal",
        "Erf",
        "Expand",
        "Flatten",
        "Gather",
        "GatherElements",
        "Greater",
        "LSTM",
        "Less",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "NonZero",
        "Not",
        "Pow",
        "Range",
        "ReduceMax",
        "ReduceMean",
        "ReduceProd",
        "ReduceSum",
        "Relu",
        "Reshape",
        "ScatterElements",
        "ScatterND",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "TopK",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/GLiNER_ITA_LARGE",
      dtype: "quantized",
      architectures: [],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLSTM",
        "DynamicQuantizeLinear",
        "Einsum",
        "Equal",
        "Erf",
        "Expand",
        "Flatten",
        "Gather",
        "GatherElements",
        "Greater",
        "Less",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "NonZero",
        "Not",
        "Pow",
        "Range",
        "ReduceMax",
        "ReduceMean",
        "ReduceProd",
        "ReduceSum",
        "Relu",
        "Reshape",
        "ScatterElements",
        "ScatterND",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "TopK",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/GLiNER_ITA_LARGE",
      dtype: "fp32",
      architectures: [],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Einsum",
        "Equal",
        "Erf",
        "Expand",
        "Flatten",
        "Gather",
        "GatherElements",
        "Greater",
        "LSTM",
        "Less",
        "MatMul",
        "Mul",
        "NonZero",
        "Not",
        "Pow",
        "Range",
        "ReduceMax",
        "ReduceMean",
        "ReduceProd",
        "ReduceSum",
        "Relu",
        "Reshape",
        "ScatterElements",
        "ScatterND",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "TopK",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
