// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "vitpose",
  models: [
    {
      model_id: "hf-internal-testing/tiny-random-VitPoseForPoseEstimation",
      dtype: "fp32",
      architectures: ["VitPoseForPoseEstimation"],
      ops: [
        "Add",
        "BatchNormalization",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "ConvTranspose",
        "Div",
        "Erf",
        "Gather",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/vitpose-base-simple",
      dtype: "q4",
      architectures: ["VitPoseForPoseEstimation"],
      ops: [
        "Add",
        "Conv",
        "Div",
        "Erf",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
      ],
    },
    {
      model_id: "onnx-community/vitpose-base-simple",
      dtype: "bnb4",
      architectures: ["VitPoseForPoseEstimation"],
      ops: [
        "Add",
        "Conv",
        "Div",
        "Erf",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
      ],
    },
    {
      model_id: "onnx-community/vitpose-base-simple",
      dtype: "q4f16",
      architectures: ["VitPoseForPoseEstimation"],
      ops: [
        "Add",
        "Cast",
        "Conv",
        "Div",
        "Erf",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
      ],
    },
    {
      model_id: "onnx-community/vitpose-base-simple",
      dtype: "quantized",
      architectures: ["VitPoseForPoseEstimation"],
      ops: [
        "Add",
        "Cast",
        "ConvInteger",
        "Div",
        "DynamicQuantizeLinear",
        "Erf",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
      ],
    },
    {
      model_id: "onnx-community/vitpose-base-simple",
      dtype: "fp32",
      architectures: ["VitPoseForPoseEstimation"],
      ops: [
        "Add",
        "Conv",
        "Div",
        "Erf",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
      ],
    },
    {
      model_id: "onnx-community/vitpose-base-simple",
      dtype: "fp16",
      architectures: ["VitPoseForPoseEstimation"],
      ops: [
        "Add",
        "Cast",
        "Conv",
        "Div",
        "Erf",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
      ],
    },
  ],
};
