// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "yolov9",
  models: [
    {
      model_id: "Xenova/gelan-c_all",
      dtype: "quantized",
      architectures: [],
      ops: [
        "Add",
        "ArgMax",
        "AveragePool",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "ConvInteger",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Expand",
        "Gather",
        "GatherND",
        "Greater",
        "MaxPool",
        "Mul",
        "NonMaxSuppression",
        "NonZero",
        "Range",
        "ReduceMax",
        "Reshape",
        "Resize",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Squeeze",
        "Sub",
        "TopK",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/gelan-c_all",
      dtype: "fp32",
      architectures: [],
      ops: [
        "Add",
        "ArgMax",
        "AveragePool",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Equal",
        "Expand",
        "Gather",
        "GatherND",
        "Greater",
        "MaxPool",
        "Mul",
        "NonMaxSuppression",
        "NonZero",
        "Range",
        "ReduceMax",
        "Reshape",
        "Resize",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Squeeze",
        "Sub",
        "TopK",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/yolov9-c_all",
      dtype: "quantized",
      architectures: [],
      ops: [
        "Add",
        "ArgMax",
        "AveragePool",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "ConvInteger",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Expand",
        "Gather",
        "GatherND",
        "Greater",
        "MaxPool",
        "Mul",
        "NonMaxSuppression",
        "NonZero",
        "Range",
        "ReduceMax",
        "ReduceSum",
        "Reshape",
        "Resize",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Squeeze",
        "Sub",
        "TopK",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/yolov9-c_all",
      dtype: "fp32",
      architectures: [],
      ops: [
        "Add",
        "ArgMax",
        "AveragePool",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Equal",
        "Expand",
        "Gather",
        "GatherND",
        "Greater",
        "MaxPool",
        "Mul",
        "NonMaxSuppression",
        "NonZero",
        "Range",
        "ReduceMax",
        "ReduceSum",
        "Reshape",
        "Resize",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Squeeze",
        "Sub",
        "TopK",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
