// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "birefnet",
  models: [
    {
      model_id: "onnx-community/BiRefNet-ONNX",
      dtype: "fp32",
      architectures: [],
      ops: [
        "Add",
        "BatchNormalization",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Floor",
        "Gather",
        "GatherND",
        "GlobalAveragePool",
        "Identity",
        "LayerNormalization",
        "MatMul",
        "Mod",
        "Mul",
        "Not",
        "Pad",
        "Relu",
        "Reshape",
        "Resize",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sub",
        "Sum",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/BiRefNet_512x512-ONNX",
      dtype: "fp32",
      architectures: [],
      ops: [
        "Add",
        "BatchNormalization",
        "Cast",
        "Ceil",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Floor",
        "Gather",
        "GatherND",
        "GlobalAveragePool",
        "Identity",
        "LayerNormalization",
        "MatMul",
        "Mod",
        "Mul",
        "Not",
        "Pad",
        "Range",
        "Relu",
        "Reshape",
        "Resize",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sub",
        "Sum",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
