// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "clap",
  models: [
    {
      model_id: "Xenova/larger_clap_music_and_speech",
      dtype: "fp32",
      architectures: ["ClapModel"],
      ops: [
        "Abs",
        "Add",
        "BatchNormalization",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "CumSum",
        "Div",
        "Equal",
        "Erf",
        "Exp",
        "Expand",
        "Flatten",
        "Gather",
        "Gemm",
        "GlobalAveragePool",
        "MatMul",
        "Mul",
        "Not",
        "Pad",
        "Pow",
        "Range",
        "ReduceMean",
        "ReduceSum",
        "Relu",
        "Reshape",
        "Resize",
        "ScatterND",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/larger_clap_music_and_speech",
      dtype: "quantized",
      architectures: ["ClapModel"],
      ops: [
        "Abs",
        "Add",
        "BatchNormalization",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "ConvInteger",
        "CumSum",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Erf",
        "Exp",
        "Expand",
        "Flatten",
        "Gather",
        "GlobalAveragePool",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Not",
        "Pad",
        "Pow",
        "Range",
        "ReduceMean",
        "ReduceSum",
        "Relu",
        "Reshape",
        "Resize",
        "ScatterND",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
