// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "glpn",
  models: [
    {
      model_id: "Xenova/glpn-kitti",
      dtype: "quantized",
      architectures: ["GLPNForDepthEstimation"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConvInteger",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Erf",
        "Gather",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/glpn-kitti",
      dtype: "fp32",
      architectures: ["GLPNForDepthEstimation"],
      ops: [
        "Add",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/glpn-kitti",
      dtype: "fp16",
      architectures: ["GLPNForDepthEstimation"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-GLPNForDepthEstimation-ONNX",
      dtype: "fp32",
      architectures: ["GLPNForDepthEstimation"],
      ops: [
        "Add",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-GLPNModel-ONNX",
      dtype: "fp32",
      architectures: ["GLPNModel"],
      ops: [
        "Add",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
  ],
};
