// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "gpt_bigcode",
  models: [
    {
      model_id: "Xenova/WizardCoder-1B-V1.0",
      dtype: "q4",
      architectures: ["GPTBigCodeForCausalLM"],
      ops: [
        "Add",
        "And",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Equal",
        "Gather",
        "If",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/WizardCoder-1B-V1.0",
      dtype: "bnb4",
      architectures: ["GPTBigCodeForCausalLM"],
      ops: [
        "Add",
        "And",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Equal",
        "Gather",
        "If",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/WizardCoder-1B-V1.0",
      dtype: "uint8",
      architectures: ["GPTBigCodeForCausalLM"],
      ops: [
        "Add",
        "And",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "CumSum",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Gather",
        "If",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/WizardCoder-1B-V1.0",
      dtype: "fp16",
      architectures: ["GPTBigCodeForCausalLM"],
      ops: [
        "Add",
        "And",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Equal",
        "Gather",
        "If",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/starcoderbase-1b",
      dtype: "quantized",
      architectures: ["GPTBigCodeForCausalLM"],
      ops: [
        "Add",
        "And",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Gather",
        "If",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/starcoderbase-1b",
      dtype: "fp32",
      architectures: ["GPTBigCodeForCausalLM"],
      ops: [
        "Add",
        "And",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Equal",
        "Gather",
        "If",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/tiny_starcoder_py",
      dtype: "q4",
      architectures: ["GPTBigCodeForCausalLM"],
      ops: [
        "Add",
        "And",
        "Cast",
        "Concat",
        "Div",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/tiny_starcoder_py",
      dtype: "quantized",
      architectures: ["GPTBigCodeForCausalLM"],
      ops: [
        "Add",
        "And",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Expand",
        "Gather",
        "If",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/tiny_starcoder_py",
      dtype: "bnb4",
      architectures: ["GPTBigCodeForCausalLM"],
      ops: [
        "Add",
        "And",
        "Cast",
        "Concat",
        "Div",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/tiny_starcoder_py",
      dtype: "fp32",
      architectures: ["GPTBigCodeForCausalLM"],
      ops: [
        "Add",
        "And",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Equal",
        "Expand",
        "Gather",
        "If",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/tiny_starcoder_py",
      dtype: "uint8",
      architectures: ["GPTBigCodeForCausalLM"],
      ops: [
        "Add",
        "And",
        "Cast",
        "Concat",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/tiny_starcoder_py",
      dtype: "fp16",
      architectures: ["GPTBigCodeForCausalLM"],
      ops: [
        "Add",
        "And",
        "Cast",
        "Concat",
        "Div",
        "Expand",
        "Gather",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "hf-internal-testing/tiny-random-GPTBigCodeForCausalLM",
      dtype: "fp32",
      architectures: ["GPTBigCodeForCausalLM"],
      ops: [
        "Add",
        "And",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Equal",
        "Expand",
        "Gather",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id:
        "onnx-internal-testing/tiny-random-GPTBigCodeForSequenceClassification-ONNX",
      dtype: "fp32",
      architectures: ["GPTBigCodeForSequenceClassification"],
      ops: [
        "Add",
        "And",
        "ArgMax",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Equal",
        "Expand",
        "Flatten",
        "Gather",
        "Identity",
        "MatMul",
        "Mod",
        "Mul",
        "Pow",
        "Range",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id:
        "onnx-internal-testing/tiny-random-GPTBigCodeForTokenClassification-ONNX",
      dtype: "fp32",
      architectures: ["GPTBigCodeForTokenClassification"],
      ops: [
        "Add",
        "And",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Equal",
        "Expand",
        "Gather",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
