// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "groupvit",
  models: [
    {
      model_id: "hf-internal-testing/tiny-random-GroupViTModel",
      dtype: "fp32",
      architectures: ["GroupViTModel"],
      ops: [
        "Add",
        "ArgMax",
        "BatchNormalization",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Equal",
        "Erf",
        "Exp",
        "Expand",
        "Flatten",
        "Gather",
        "Gemm",
        "Identity",
        "Less",
        "MatMul",
        "Mul",
        "Pow",
        "Range",
        "ReduceL2",
        "ReduceMean",
        "ReduceSum",
        "Relu",
        "Reshape",
        "ScatterElements",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
