// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "gte",
  models: [
    {
      model_id: "Snowflake/snowflake-arctic-embed-m-v2.0",
      dtype: "q4",
      architectures: ["GteModel"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Neg",
        "Pow",
        "ReduceL2",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Snowflake/snowflake-arctic-embed-m-v2.0",
      dtype: "bnb4",
      architectures: ["GteModel"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "Neg",
        "Pow",
        "ReduceL2",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Snowflake/snowflake-arctic-embed-m-v2.0",
      dtype: "quantized",
      architectures: ["GteModel"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Neg",
        "Pow",
        "ReduceL2",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Snowflake/snowflake-arctic-embed-m-v2.0",
      dtype: "fp32",
      architectures: ["GteModel"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "Mul",
        "Neg",
        "Pow",
        "ReduceL2",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
