// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "hiera",
  models: [
    {
      model_id: "hf-internal-testing/tiny-random-HieraForImageClassification",
      dtype: "fp32",
      architectures: ["HieraForImageClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Flatten",
        "Gather",
        "Gemm",
        "GlobalAveragePool",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMax",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/hiera-base-plus-224-in1k-hf",
      dtype: "q4",
      architectures: ["HieraForImageClassification"],
      ops: [
        "Add",
        "Concat",
        "Conv",
        "Div",
        "Erf",
        "Flatten",
        "Gather",
        "Gemm",
        "GlobalAveragePool",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Pow",
        "ReduceMax",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/hiera-base-plus-224-in1k-hf",
      dtype: "bnb4",
      architectures: ["HieraForImageClassification"],
      ops: [
        "Add",
        "Concat",
        "Conv",
        "Div",
        "Erf",
        "Flatten",
        "Gather",
        "Gemm",
        "GlobalAveragePool",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "Pow",
        "ReduceMax",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/hiera-base-plus-224-in1k-hf",
      dtype: "q4f16",
      architectures: ["HieraForImageClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Conv",
        "Div",
        "Erf",
        "Flatten",
        "Gather",
        "Gemm",
        "GlobalAveragePool",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Pow",
        "ReduceMax",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/hiera-base-plus-224-in1k-hf",
      dtype: "quantized",
      architectures: ["HieraForImageClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConvInteger",
        "Div",
        "DynamicQuantizeLinear",
        "Erf",
        "Flatten",
        "Gather",
        "GlobalAveragePool",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pow",
        "ReduceMax",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/hiera-base-plus-224-in1k-hf",
      dtype: "fp32",
      architectures: ["HieraForImageClassification"],
      ops: [
        "Add",
        "Concat",
        "Conv",
        "Div",
        "Erf",
        "Flatten",
        "Gather",
        "Gemm",
        "GlobalAveragePool",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMax",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/hiera-base-plus-224-in1k-hf",
      dtype: "fp16",
      architectures: ["HieraForImageClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Conv",
        "Div",
        "Erf",
        "Flatten",
        "Gather",
        "Gemm",
        "GlobalAveragePool",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMax",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/hiera-small-224-hf",
      dtype: "q4",
      architectures: ["HieraModel"],
      ops: [
        "Add",
        "Concat",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Pow",
        "ReduceMax",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/hiera-small-224-hf",
      dtype: "bnb4",
      architectures: ["HieraModel"],
      ops: [
        "Add",
        "Concat",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "Pow",
        "ReduceMax",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/hiera-small-224-hf",
      dtype: "q4f16",
      architectures: ["HieraModel"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Pow",
        "ReduceMax",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/hiera-small-224-hf",
      dtype: "quantized",
      architectures: ["HieraModel"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConvInteger",
        "Div",
        "DynamicQuantizeLinear",
        "Erf",
        "Gather",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pow",
        "ReduceMax",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/hiera-small-224-hf",
      dtype: "fp32",
      architectures: ["HieraModel"],
      ops: [
        "Add",
        "Concat",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMax",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/hiera-small-224-hf",
      dtype: "fp16",
      architectures: ["HieraModel"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMax",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
  ],
};
