// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "jais",
  models: [
    {
      model_id: "onnx-community/jais-family-590m-chat",
      dtype: "quantized",
      architectures: ["JAISLMHeadModel"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/jais-family-590m-chat",
      dtype: "fp32",
      architectures: ["JAISLMHeadModel"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Div",
        "Expand",
        "Gather",
        "Gemm",
        "MatMul",
        "Mul",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/tiny-random-jais",
      dtype: "fp32",
      architectures: ["JAISLMHeadModel"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Equal",
        "Expand",
        "Gather",
        "Gemm",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
