// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "layoutlmv3",
  models: [
    {
      model_id:
        "onnx-internal-testing/tiny-random-LayoutLMv3ForSequenceClassification-ONNX",
      dtype: "fp32",
      architectures: ["LayoutLMv3ForSequenceClassification"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "CumSum",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Gemm",
        "Greater",
        "Identity",
        "Less",
        "Log",
        "MatMul",
        "Min",
        "Mul",
        "Not",
        "Pow",
        "Range",
        "ReduceMax",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id:
        "onnx-internal-testing/tiny-random-LayoutLMv3ForTokenClassification-ONNX",
      dtype: "fp32",
      architectures: ["LayoutLMv3ForTokenClassification"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "CumSum",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Greater",
        "Identity",
        "Less",
        "Log",
        "MatMul",
        "Min",
        "Mul",
        "Not",
        "Pow",
        "Range",
        "ReduceMax",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
