// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "levit",
  models: [
    {
      model_id:
        "onnx-internal-testing/tiny-random-LevitForImageClassification-ONNX",
      dtype: "fp32",
      architectures: ["LevitForImageClassification"],
      ops: [
        "Add",
        "BatchNormalization",
        "Concat",
        "Constant",
        "Conv",
        "Flatten",
        "Gather",
        "Gemm",
        "HardSigmoid",
        "Identity",
        "MatMul",
        "Mul",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id:
        "onnx-internal-testing/tiny-random-LevitForImageClassificationWithTeacher-ONNX",
      dtype: "fp32",
      architectures: ["LevitForImageClassificationWithTeacher"],
      ops: [
        "Add",
        "BatchNormalization",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Flatten",
        "Gather",
        "Gemm",
        "HardSigmoid",
        "Identity",
        "MatMul",
        "Mul",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-LevitModel-ONNX",
      dtype: "fp32",
      architectures: ["LevitModel"],
      ops: [
        "Add",
        "BatchNormalization",
        "Concat",
        "Constant",
        "Conv",
        "Flatten",
        "Gather",
        "HardSigmoid",
        "Identity",
        "MatMul",
        "Mul",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Transpose",
        "Unsqueeze",
      ],
    },
  ],
};
