// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "mctct",
  models: [
    {
      model_id: "onnx-internal-testing/tiny-random-MCTCTForCTC-ONNX",
      dtype: "fp32",
      architectures: ["MCTCTForCTC"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Einsum",
        "Gather",
        "Identity",
        "MatMul",
        "Mul",
        "Pad",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
  ],
};
