// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "metric3d",
  models: [
    {
      model_id: "onnx-community/metric3d-vit-giant2",
      dtype: "fp32",
      architectures: [],
      ops: [
        "Add",
        "AveragePool",
        "Cast",
        "Concat",
        "Conv",
        "ConvTranspose",
        "Div",
        "Elu",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "Mul",
        "Pad",
        "Pow",
        "Range",
        "ReduceMean",
        "ReduceSum",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/metric3d-vit-small",
      dtype: "fp32",
      architectures: [],
      ops: [
        "Add",
        "AveragePool",
        "Cast",
        "Concat",
        "ConstantOfShape",
        "Conv",
        "ConvTranspose",
        "Div",
        "Elu",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "Mul",
        "Pad",
        "Pow",
        "Range",
        "ReduceMean",
        "ReduceSum",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
