// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "mimi",
  models: [
    {
      model_id: "hf-internal-testing/tiny-random-MimiModel",
      dtype: "fp32",
      architectures: ["MimiModel"],
      ops: [
        "Add",
        "ArgMin",
        "Cast",
        "Ceil",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Cos",
        "Div",
        "Elu",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Identity",
        "MatMul",
        "Mul",
        "Neg",
        "Pad",
        "Pow",
        "Range",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/kyutai-mimi-ONNX",
      dtype: "int8",
      architectures: ["MimiModel"],
      ops: [
        "Add",
        "ArgMin",
        "Cast",
        "Ceil",
        "Concat",
        "ConvInteger",
        "Cos",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Elu",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Neg",
        "Pad",
        "Pow",
        "Range",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/kyutai-mimi-ONNX",
      dtype: "q4f16",
      architectures: ["MimiModel"],
      ops: [
        "Add",
        "ArgMin",
        "Cast",
        "Ceil",
        "Concat",
        "Conv",
        "Cos",
        "Div",
        "Elu",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Neg",
        "Pad",
        "Pow",
        "Range",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/kyutai-mimi-ONNX",
      dtype: "bnb4",
      architectures: ["MimiModel"],
      ops: [
        "Add",
        "ArgMin",
        "Cast",
        "Ceil",
        "Concat",
        "Conv",
        "Cos",
        "Div",
        "Elu",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "Neg",
        "Pad",
        "Pow",
        "Range",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/kyutai-mimi-ONNX",
      dtype: "fp16",
      architectures: ["MimiModel"],
      ops: [
        "Add",
        "ArgMin",
        "Cast",
        "Ceil",
        "Concat",
        "Conv",
        "Cos",
        "Div",
        "Elu",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "Mul",
        "Neg",
        "Pad",
        "Pow",
        "Range",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
