// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "mobilenet_v4",
  models: [
    {
      model_id: "onnx-community/mobilenetv4_conv_small.e2400_r224_in1k",
      dtype: "q4",
      architectures: [],
      ops: ["Add", "Conv", "Flatten", "Gemm", "GlobalAveragePool", "Relu"],
    },
    {
      model_id: "onnx-community/mobilenetv4_conv_small.e2400_r224_in1k",
      dtype: "quantized",
      architectures: [],
      ops: [
        "Add",
        "Cast",
        "ConvInteger",
        "DynamicQuantizeLinear",
        "Flatten",
        "GlobalAveragePool",
        "MatMulInteger",
        "Mul",
        "Relu",
        "Reshape",
      ],
    },
    {
      model_id: "onnx-community/mobilenetv4_conv_small.e2400_r224_in1k",
      dtype: "fp16",
      architectures: [],
      ops: [
        "Add",
        "Cast",
        "Conv",
        "Flatten",
        "Gemm",
        "GlobalAveragePool",
        "Relu",
      ],
    },
    {
      model_id: "onnx-community/mobilenetv4_hybrid_large.e600_r384_in1k",
      dtype: "q4",
      architectures: [],
      ops: [
        "Add",
        "BatchNormalization",
        "Concat",
        "Conv",
        "Div",
        "Erf",
        "Flatten",
        "Gather",
        "Gemm",
        "GlobalAveragePool",
        "MatMul",
        "Mul",
        "Reshape",
        "Shape",
        "Softmax",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/mobilenetv4_hybrid_large.e600_r384_in1k",
      dtype: "quantized",
      architectures: [],
      ops: [
        "Add",
        "BatchNormalization",
        "Cast",
        "Concat",
        "ConvInteger",
        "Div",
        "DynamicQuantizeLinear",
        "Erf",
        "Flatten",
        "Gather",
        "GlobalAveragePool",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Reshape",
        "Shape",
        "Softmax",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/mobilenetv4_hybrid_large.e600_r384_in1k",
      dtype: "fp16",
      architectures: [],
      ops: [
        "Add",
        "BatchNormalization",
        "Cast",
        "Concat",
        "Conv",
        "Div",
        "Erf",
        "Flatten",
        "Gather",
        "Gemm",
        "GlobalAveragePool",
        "MatMul",
        "Mul",
        "Reshape",
        "Shape",
        "Softmax",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/mobilenetv4_hybrid_medium.e500_r224_in1k",
      dtype: "q4",
      architectures: [],
      ops: [
        "Add",
        "BatchNormalization",
        "Concat",
        "Conv",
        "Div",
        "Flatten",
        "Gather",
        "Gemm",
        "GlobalAveragePool",
        "MatMul",
        "Mul",
        "Relu",
        "Reshape",
        "Shape",
        "Softmax",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/mobilenetv4_hybrid_medium.e500_r224_in1k",
      dtype: "quantized",
      architectures: [],
      ops: [
        "Add",
        "BatchNormalization",
        "Cast",
        "Concat",
        "ConvInteger",
        "Div",
        "DynamicQuantizeLinear",
        "Flatten",
        "Gather",
        "GlobalAveragePool",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Relu",
        "Reshape",
        "Shape",
        "Softmax",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/mobilenetv4_hybrid_medium.e500_r224_in1k",
      dtype: "fp16",
      architectures: [],
      ops: [
        "Add",
        "BatchNormalization",
        "Cast",
        "Concat",
        "Conv",
        "Div",
        "Flatten",
        "Gather",
        "Gemm",
        "GlobalAveragePool",
        "MatMul",
        "Mul",
        "Relu",
        "Reshape",
        "Shape",
        "Softmax",
        "Transpose",
        "Unsqueeze",
      ],
    },
  ],
};
