// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "mobilebert",
  models: [
    {
      model_id: "Xenova/mobilebert-uncased-mnli",
      dtype: "quantized",
      architectures: ["MobileBertForSequenceClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Gather",
        "Identity",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pad",
        "Relu",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/mobilebert-uncased-mnli",
      dtype: "fp32",
      architectures: ["MobileBertForSequenceClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Gather",
        "Gemm",
        "Identity",
        "MatMul",
        "Mul",
        "Pad",
        "Relu",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "hf-internal-testing/tiny-random-MobileBertForMaskedLM",
      dtype: "fp32",
      architectures: ["MobileBertForMaskedLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Erf",
        "Gather",
        "Identity",
        "MatMul",
        "Mul",
        "Pad",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id:
        "hf-internal-testing/tiny-random-MobileBertForQuestionAnswering",
      dtype: "fp32",
      architectures: ["MobileBertForQuestionAnswering"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Erf",
        "Gather",
        "Identity",
        "MatMul",
        "Mul",
        "Pad",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id:
        "hf-internal-testing/tiny-random-MobileBertForSequenceClassification",
      dtype: "fp32",
      architectures: ["MobileBertForSequenceClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Erf",
        "Gather",
        "Gemm",
        "Identity",
        "MatMul",
        "Mul",
        "Pad",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "hf-internal-testing/tiny-random-MobileBertModel",
      dtype: "fp32",
      architectures: ["MobileBertModel"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Erf",
        "Gather",
        "Identity",
        "MatMul",
        "Mul",
        "Pad",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id:
        "onnx-internal-testing/tiny-random-MobileBertForMultipleChoice-ONNX",
      dtype: "fp32",
      architectures: ["MobileBertForMultipleChoice"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Erf",
        "Gather",
        "Gemm",
        "Identity",
        "MatMul",
        "Mul",
        "Pad",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Squeeze",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
      ],
    },
  ],
};
