// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "mobilenet_v2",
  models: [
    {
      model_id: "onnx-community/mobilenet_v2_1.0_224",
      dtype: "q4",
      architectures: ["MobileNetV2ForImageClassification"],
      ops: ["Add", "Clip", "Conv", "Flatten", "Gemm", "GlobalAveragePool"],
    },
    {
      model_id: "onnx-community/mobilenet_v2_1.0_224",
      dtype: "quantized",
      architectures: ["MobileNetV2ForImageClassification"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "ConvInteger",
        "DynamicQuantizeLinear",
        "Flatten",
        "GlobalAveragePool",
        "MatMulInteger",
        "Mul",
        "Reshape",
      ],
    },
    {
      model_id: "onnx-community/mobilenet_v2_1.0_224",
      dtype: "fp16",
      architectures: ["MobileNetV2ForImageClassification"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Conv",
        "Flatten",
        "Gemm",
        "GlobalAveragePool",
      ],
    },
    {
      model_id:
        "onnx-internal-testing/tiny-random-MobileNetV2ForImageClassification-ONNX",
      dtype: "fp32",
      architectures: ["MobileNetV2ForImageClassification"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Flatten",
        "Gemm",
        "GlobalAveragePool",
        "Identity",
        "Pad",
        "Reshape",
        "Slice",
        "Transpose",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-MobileNetV2Model-ONNX",
      dtype: "fp32",
      architectures: ["MobileNetV2Model"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Identity",
        "Pad",
        "Reshape",
        "Slice",
        "Transpose",
      ],
    },
  ],
};
