// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "movenet",
  models: [
    {
      model_id: "Xenova/movenet-multipose-lightning",
      dtype: "q4",
      architectures: [],
      ops: [
        "Abs",
        "Add",
        "And",
        "ArgMax",
        "BatchNormalization",
        "Cast",
        "Clip",
        "Concat",
        "Conv",
        "Div",
        "Equal",
        "Exp",
        "Expand",
        "Gather",
        "GatherND",
        "Greater",
        "Less",
        "Max",
        "MaxPool",
        "Min",
        "Mul",
        "Not",
        "Pow",
        "Range",
        "Reciprocal",
        "ReduceMax",
        "ReduceSum",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Size",
        "Slice",
        "Split",
        "Squeeze",
        "Sub",
        "Tile",
        "TopK",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/movenet-multipose-lightning",
      dtype: "quantized",
      architectures: [],
      ops: [
        "Abs",
        "Add",
        "And",
        "ArgMax",
        "BatchNormalization",
        "Cast",
        "Clip",
        "Concat",
        "ConvInteger",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Exp",
        "Expand",
        "Gather",
        "GatherND",
        "Greater",
        "Less",
        "Max",
        "MaxPool",
        "Min",
        "Mul",
        "Not",
        "Pow",
        "Range",
        "Reciprocal",
        "ReduceMax",
        "ReduceSum",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Size",
        "Slice",
        "Split",
        "Squeeze",
        "Sub",
        "Tile",
        "TopK",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/movenet-singlepose-lightning",
      dtype: "q4",
      architectures: [],
      ops: [
        "Add",
        "ArgMax",
        "BatchNormalization",
        "Cast",
        "Clip",
        "Concat",
        "Conv",
        "Div",
        "GatherND",
        "Mul",
        "Pow",
        "Relu",
        "Reshape",
        "Resize",
        "Sigmoid",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/movenet-singlepose-lightning",
      dtype: "quantized",
      architectures: [],
      ops: [
        "Add",
        "ArgMax",
        "BatchNormalization",
        "Cast",
        "Clip",
        "Concat",
        "ConvInteger",
        "Div",
        "DynamicQuantizeLinear",
        "GatherND",
        "Mul",
        "Pow",
        "Relu",
        "Reshape",
        "Resize",
        "Sigmoid",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
  ],
};
