// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "multi_modality",
  models: [
    {
      model_id: "onnx-community/Janus-Pro-1B-ONNX",
      dtype: "q4f16",
      architectures: ["MultiModalityCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "GatherND",
        "InstanceNormalization",
        "Less",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "MultiHeadAttention",
        "NonZero",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Resize",
        "RotaryEmbedding",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/Janus-Pro-1B-ONNX",
      dtype: "fp16",
      architectures: ["MultiModalityCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "GatherND",
        "InstanceNormalization",
        "Less",
        "MatMul",
        "Mul",
        "MultiHeadAttention",
        "NonZero",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Resize",
        "RotaryEmbedding",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/Janus-Pro-1B-ONNX",
      dtype: "bnb4",
      architectures: ["MultiModalityCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "GatherND",
        "InstanceNormalization",
        "Less",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "MultiHeadAttention",
        "NonZero",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Resize",
        "RotaryEmbedding",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/Janus-Pro-1B-ONNX",
      dtype: "uint8",
      architectures: ["MultiModalityCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "ConvInteger",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "GatherND",
        "InstanceNormalization",
        "Less",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "MultiHeadAttention",
        "NonZero",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Resize",
        "RotaryEmbedding",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/Janus-Pro-1B-ONNX",
      dtype: "q4",
      architectures: ["MultiModalityCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Expand",
        "Gather",
        "GatherND",
        "GroupQueryAttention",
        "InstanceNormalization",
        "Less",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "NonZero",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Resize",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
