// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "patchtst",
  models: [
    {
      model_id: "hf-internal-testing/tiny-random-PatchTSTModel",
      dtype: "q4",
      architectures: ["PatchTSTModel"],
      ops: [
        "Add",
        "BatchNormalization",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Pow",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "hf-internal-testing/tiny-random-PatchTSTModel",
      dtype: "bnb4",
      architectures: ["PatchTSTModel"],
      ops: [
        "Add",
        "BatchNormalization",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "Pow",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "hf-internal-testing/tiny-random-PatchTSTModel",
      dtype: "q4f16",
      architectures: ["PatchTSTModel"],
      ops: [
        "Add",
        "BatchNormalization",
        "Cast",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Pow",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "hf-internal-testing/tiny-random-PatchTSTModel",
      dtype: "quantized",
      architectures: ["PatchTSTModel"],
      ops: [
        "Add",
        "BatchNormalization",
        "Cast",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pow",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "hf-internal-testing/tiny-random-PatchTSTModel",
      dtype: "fp32",
      architectures: ["PatchTSTModel"],
      ops: [
        "Add",
        "BatchNormalization",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "hf-internal-testing/tiny-random-PatchTSTModel",
      dtype: "fp16",
      architectures: ["PatchTSTModel"],
      ops: [
        "Add",
        "BatchNormalization",
        "Cast",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
