// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "patchtsmixer",
  models: [
    {
      model_id: "hf-internal-testing/tiny-random-PatchTSMixerModel",
      dtype: "q4",
      architectures: ["PatchTSMixerModel"],
      ops: [
        "Add",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "Div",
        "Erf",
        "MatMulNBits",
        "Mul",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "hf-internal-testing/tiny-random-PatchTSMixerModel",
      dtype: "bnb4",
      architectures: ["PatchTSMixerModel"],
      ops: [
        "Add",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "Div",
        "Erf",
        "MatMulBnb4",
        "Mul",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "hf-internal-testing/tiny-random-PatchTSMixerModel",
      dtype: "q4f16",
      architectures: ["PatchTSMixerModel"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "Div",
        "Erf",
        "MatMulNBits",
        "Mul",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "hf-internal-testing/tiny-random-PatchTSMixerModel",
      dtype: "quantized",
      architectures: ["PatchTSMixerModel"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "Div",
        "DynamicQuantizeLinear",
        "Erf",
        "MatMulInteger",
        "Mul",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "hf-internal-testing/tiny-random-PatchTSMixerModel",
      dtype: "fp32",
      architectures: ["PatchTSMixerModel"],
      ops: [
        "Add",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "Div",
        "Erf",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "hf-internal-testing/tiny-random-PatchTSMixerModel",
      dtype: "fp16",
      architectures: ["PatchTSMixerModel"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "Div",
        "Erf",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/granite-timeseries-patchtsmixer",
      dtype: "q4",
      architectures: ["PatchTSMixerForPrediction"],
      ops: [
        "Add",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "Div",
        "Erf",
        "MatMulNBits",
        "Mul",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/granite-timeseries-patchtsmixer",
      dtype: "bnb4",
      architectures: ["PatchTSMixerForPrediction"],
      ops: [
        "Add",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "Div",
        "Erf",
        "MatMulBnb4",
        "Mul",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/granite-timeseries-patchtsmixer",
      dtype: "q4f16",
      architectures: ["PatchTSMixerForPrediction"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "Div",
        "Erf",
        "MatMulNBits",
        "Mul",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/granite-timeseries-patchtsmixer",
      dtype: "quantized",
      architectures: ["PatchTSMixerForPrediction"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "Div",
        "DynamicQuantizeLinear",
        "Erf",
        "MatMulInteger",
        "Mul",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/granite-timeseries-patchtsmixer",
      dtype: "fp32",
      architectures: ["PatchTSMixerForPrediction"],
      ops: [
        "Add",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "Div",
        "Erf",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/granite-timeseries-patchtsmixer",
      dtype: "fp16",
      architectures: ["PatchTSMixerForPrediction"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "Div",
        "Erf",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-PatchTSMixerModel-ONNX",
      dtype: "fp32",
      architectures: ["PatchTSMixerModel"],
      ops: [
        "Add",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Erf",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
  ],
};
