// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "phi3",
  models: [
    {
      model_id: "Xenova/Phi-3-mini-4k-instruct_fp16",
      dtype: "q4",
      architectures: ["Phi3ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Equal",
        "Expand",
        "Gather",
        "Less",
        "MatMulNBits",
        "Mul",
        "MultiHeadAttention",
        "Range",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Slice",
        "Squeeze",
        "Sub",
        "Tile",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/tiny-random-Phi3ForCausalLM",
      dtype: "q4",
      architectures: ["Phi3ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Cos",
        "Div",
        "Equal",
        "Expand",
        "Gather",
        "Identity",
        "Less",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Sin",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/tiny-random-Phi3ForCausalLM",
      dtype: "bnb4",
      architectures: ["Phi3ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Cos",
        "Div",
        "Equal",
        "Expand",
        "Gather",
        "Identity",
        "Less",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Sin",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/tiny-random-Phi3ForCausalLM",
      dtype: "quantized",
      architectures: ["Phi3ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Cos",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Expand",
        "Gather",
        "Identity",
        "Less",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Sin",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/tiny-random-Phi3ForCausalLM",
      dtype: "fp32",
      architectures: ["Phi3ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Cos",
        "Div",
        "Equal",
        "Expand",
        "Gather",
        "Identity",
        "Less",
        "MatMul",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Sin",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/Phi-3.5-mini-instruct-ONNX-GQA",
      dtype: "q4",
      architectures: ["Phi3ForCausalLM"],
      ops: [
        "Cast",
        "Constant",
        "Gather",
        "Greater",
        "GroupQueryAttention",
        "If",
        "MatMulNBits",
        "Mul",
        "ReduceSum",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Sub",
      ],
    },
    {
      model_id: "onnx-community/Phi-3.5-mini-instruct-ONNX-GQA",
      dtype: "q4f16",
      architectures: ["Phi3ForCausalLM"],
      ops: [
        "Cast",
        "Concat",
        "Constant",
        "Gather",
        "Greater",
        "GroupQueryAttention",
        "If",
        "MatMulNBits",
        "Mul",
        "ReduceSum",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Sub",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/Phi-3.5-mini-instruct-ONNX-GQA",
      dtype: "fp32",
      architectures: ["Phi3ForCausalLM"],
      ops: [
        "Cast",
        "Concat",
        "Constant",
        "Gather",
        "Greater",
        "GroupQueryAttention",
        "If",
        "MatMul",
        "Mul",
        "ReduceSum",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Sub",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/Phi-3.5-mini-instruct-onnx-web",
      dtype: "q4f16",
      architectures: ["Phi3ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Equal",
        "Expand",
        "Gather",
        "Greater",
        "If",
        "Less",
        "MatMulNBits",
        "Mul",
        "MultiHeadAttention",
        "Range",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Slice",
        "Squeeze",
        "Sub",
        "Tile",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/Phi-4-mini-instruct-ONNX-GQA",
      dtype: "q4",
      architectures: ["Phi3ForCausalLM"],
      ops: [
        "Cast",
        "Concat",
        "Constant",
        "Gather",
        "Greater",
        "GroupQueryAttention",
        "If",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "ReduceSum",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/Phi-4-mini-instruct-ONNX-GQA",
      dtype: "fp32",
      architectures: ["Phi3ForCausalLM"],
      ops: [
        "Cast",
        "Concat",
        "Constant",
        "Gather",
        "Greater",
        "GroupQueryAttention",
        "If",
        "MatMul",
        "Mul",
        "ReduceSum",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/Phi-4-mini-instruct-ONNX-MHA",
      dtype: "q4",
      architectures: ["Phi3ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Equal",
        "Expand",
        "Gather",
        "Greater",
        "If",
        "Less",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "MultiHeadAttention",
        "Range",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Slice",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-community/Phi-4-mini-instruct-ONNX-MHA",
      dtype: "fp32",
      architectures: ["Phi3ForCausalLM"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Equal",
        "Expand",
        "Gather",
        "Greater",
        "If",
        "Less",
        "MatMul",
        "Mul",
        "MultiHeadAttention",
        "Range",
        "Reshape",
        "RotaryEmbedding",
        "Shape",
        "Sigmoid",
        "SimplifiedLayerNormalization",
        "SkipSimplifiedLayerNormalization",
        "Slice",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
