// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "rtmo",
  models: [
    {
      model_id: "Xenova/RTMO-m",
      dtype: "q4",
      architectures: [],
      ops: [
        "Abs",
        "Add",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "Conv",
        "Cos",
        "Div",
        "Equal",
        "Erf",
        "Exp",
        "Expand",
        "Flatten",
        "Gather",
        "Gemm",
        "Less",
        "MatMul",
        "MatMulNBits",
        "MaxPool",
        "Mul",
        "Neg",
        "NonMaxSuppression",
        "Pow",
        "Range",
        "ReduceMax",
        "ReduceMean",
        "ReduceSum",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Sin",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Sub",
        "Tile",
        "TopK",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/RTMO-m",
      dtype: "bnb4",
      architectures: [],
      ops: [
        "Abs",
        "Add",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "Conv",
        "Cos",
        "Div",
        "Equal",
        "Erf",
        "Exp",
        "Expand",
        "Flatten",
        "Gather",
        "Gemm",
        "Less",
        "MatMul",
        "MatMulBnb4",
        "MaxPool",
        "Mul",
        "Neg",
        "NonMaxSuppression",
        "Pow",
        "Range",
        "ReduceMax",
        "ReduceMean",
        "ReduceSum",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Sin",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Sub",
        "Tile",
        "TopK",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/RTMO-m",
      dtype: "quantized",
      architectures: [],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "ConvInteger",
        "Cos",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Erf",
        "Exp",
        "Expand",
        "Flatten",
        "Gather",
        "Less",
        "MatMul",
        "MatMulInteger",
        "MaxPool",
        "Mul",
        "Neg",
        "NonMaxSuppression",
        "Pow",
        "Range",
        "ReduceMax",
        "ReduceMean",
        "ReduceSum",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Sin",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Sub",
        "Tile",
        "TopK",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/RTMO-m",
      dtype: "fp32",
      architectures: [],
      ops: [
        "Abs",
        "Add",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "Conv",
        "Cos",
        "Div",
        "Equal",
        "Erf",
        "Exp",
        "Expand",
        "Flatten",
        "Gather",
        "Gemm",
        "Less",
        "MatMul",
        "MaxPool",
        "Mul",
        "Neg",
        "NonMaxSuppression",
        "Pow",
        "Range",
        "ReduceMax",
        "ReduceMean",
        "ReduceSum",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Sin",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Sub",
        "Tile",
        "TopK",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/RTMO-m",
      dtype: "fp16",
      architectures: [],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "ConstantOfShape",
        "Conv",
        "Cos",
        "Div",
        "Equal",
        "Erf",
        "Exp",
        "Expand",
        "Flatten",
        "Gather",
        "Gemm",
        "Less",
        "MatMul",
        "MaxPool",
        "Mul",
        "Neg",
        "NonMaxSuppression",
        "Pow",
        "Range",
        "ReduceMax",
        "ReduceMean",
        "ReduceSum",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Sin",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Sub",
        "Tile",
        "TopK",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
