// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "sew-d",
  models: [
    {
      model_id: "onnx-internal-testing/tiny-random-SEWDForCTC-ONNX",
      dtype: "fp32",
      architectures: ["SEWDForCTC"],
      ops: [
        "Abs",
        "Add",
        "And",
        "AveragePool",
        "Cast",
        "Ceil",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "GatherElements",
        "Greater",
        "Identity",
        "InstanceNormalization",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "Mul",
        "Neg",
        "Pad",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sign",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id:
        "onnx-internal-testing/tiny-random-SEWDForSequenceClassification-ONNX",
      dtype: "fp32",
      architectures: ["SEWDForSequenceClassification"],
      ops: [
        "Abs",
        "Add",
        "And",
        "AveragePool",
        "Cast",
        "Ceil",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "GatherElements",
        "Gemm",
        "Greater",
        "Identity",
        "InstanceNormalization",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "Mul",
        "Neg",
        "Pad",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sign",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
