// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "speecht5",
  models: [
    {
      model_id: "Xenova/speecht5_tts",
      dtype: "fp16",
      architectures: ["SpeechT5ForTextToSpeech"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Greater",
        "If",
        "Less",
        "MatMul",
        "Mul",
        "Not",
        "Pow",
        "RandomUniformLike",
        "Range",
        "ReduceMean",
        "ReduceSum",
        "Relu",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/speecht5_tts",
      dtype: "quantized",
      architectures: ["SpeechT5ForTextToSpeech"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "ConvInteger",
        "ConvTranspose",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Greater",
        "If",
        "LeakyRelu",
        "Less",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Not",
        "Pow",
        "RandomUniformLike",
        "Range",
        "ReduceMean",
        "ReduceSum",
        "Relu",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/speecht5_tts",
      dtype: "fp32",
      architectures: ["SpeechT5ForTextToSpeech"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "ConvTranspose",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Greater",
        "If",
        "LeakyRelu",
        "Less",
        "MatMul",
        "Mul",
        "Not",
        "Pow",
        "RandomUniformLike",
        "Range",
        "ReduceMean",
        "ReduceSum",
        "Relu",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
