// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "speech_to_text",
  models: [
    {
      model_id: "onnx-internal-testing/tiny-random-Speech2TextModel-ONNX",
      dtype: "fp32",
      architectures: ["Speech2TextModel"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Cos",
        "CumSum",
        "Div",
        "Equal",
        "Expand",
        "Gather",
        "Identity",
        "If",
        "Less",
        "MatMul",
        "Mul",
        "Not",
        "Pow",
        "Range",
        "ReduceMean",
        "ReduceSum",
        "Relu",
        "Reshape",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "Sin",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
