// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "swinv2",
  models: [
    {
      model_id:
        "onnx-internal-testing/tiny-random-Swinv2ForImageClassification-ONNX",
      dtype: "fp32",
      architectures: ["Swinv2ForImageClassification"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Equal",
        "Erf",
        "Exp",
        "Expand",
        "Flatten",
        "Gather",
        "Gemm",
        "GlobalAveragePool",
        "Identity",
        "MatMul",
        "Mod",
        "Mul",
        "Not",
        "Pad",
        "Pow",
        "Range",
        "ReduceL2",
        "ReduceMean",
        "Relu",
        "Reshape",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-Swinv2Model-ONNX",
      dtype: "fp32",
      architectures: ["Swinv2Model"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Equal",
        "Erf",
        "Exp",
        "Expand",
        "Gather",
        "Identity",
        "MatMul",
        "Mod",
        "Mul",
        "Not",
        "Pad",
        "Pow",
        "Range",
        "ReduceL2",
        "ReduceMean",
        "Relu",
        "Reshape",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
