// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "t5",
  models: [
    {
      model_id: "Xenova/flan-t5-small",
      dtype: "fp16",
      architectures: ["T5ForConditionalGeneration"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Expand",
        "Gather",
        "Greater",
        "If",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "Min",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/flan-t5-small",
      dtype: "quantized",
      architectures: ["T5ForConditionalGeneration"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Expand",
        "Gather",
        "Greater",
        "If",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "MatMulInteger",
        "Min",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/instructor-large",
      dtype: "quantized",
      architectures: ["T5EncoderModel"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Expand",
        "Gather",
        "Greater",
        "Identity",
        "If",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "MatMulInteger",
        "Min",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/propositionizer-wiki-flan-t5-large",
      dtype: "q4f16",
      architectures: ["T5ForConditionalGeneration"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Expand",
        "Gather",
        "Greater",
        "If",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "MatMulNBits",
        "Min",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/propositionizer-wiki-flan-t5-large",
      dtype: "bnb4",
      architectures: ["T5ForConditionalGeneration"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Expand",
        "Gather",
        "Greater",
        "If",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "MatMulBnb4",
        "Min",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/t5-base-grammar-correction",
      dtype: "bnb4",
      architectures: ["T5ForConditionalGeneration"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Expand",
        "Gather",
        "Greater",
        "If",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "MatMulBnb4",
        "Min",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/t5-base-grammar-correction",
      dtype: "q4",
      architectures: ["T5ForConditionalGeneration"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Expand",
        "Gather",
        "Greater",
        "If",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "MatMulNBits",
        "Min",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/t5-small",
      dtype: "fp16",
      architectures: ["T5ForConditionalGeneration"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Expand",
        "Gather",
        "Greater",
        "If",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "Min",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/t5-small",
      dtype: "quantized",
      architectures: ["T5ForConditionalGeneration"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Expand",
        "Gather",
        "Greater",
        "If",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "MatMulInteger",
        "Min",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "hf-internal-testing/tiny-random-T5ForConditionalGeneration",
      dtype: "fp32",
      architectures: ["T5ForConditionalGeneration"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Expand",
        "Gather",
        "Greater",
        "Identity",
        "If",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "Min",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-t5-ONNX",
      dtype: "fp32",
      architectures: [],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Equal",
        "Expand",
        "Gather",
        "Greater",
        "Identity",
        "If",
        "Less",
        "Log",
        "MatMul",
        "Min",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Relu",
        "Reshape",
        "ScatterND",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "teapotai/teapotllm",
      dtype: "fp16",
      architectures: ["T5ForConditionalGeneration"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Equal",
        "Expand",
        "Gather",
        "Greater",
        "If",
        "Less",
        "Log",
        "MatMul",
        "Min",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "ScatterND",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "teapotai/teapotllm",
      dtype: "quantized",
      architectures: ["T5ForConditionalGeneration"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Expand",
        "Gather",
        "Greater",
        "If",
        "Less",
        "Log",
        "MatMul",
        "MatMulInteger",
        "Min",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "ScatterND",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "teapotai/teapotllm",
      dtype: "q4f16",
      architectures: ["T5ForConditionalGeneration"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Equal",
        "Expand",
        "Gather",
        "Greater",
        "If",
        "Less",
        "Log",
        "MatMul",
        "MatMulNBits",
        "Min",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "ScatterND",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "teapotai/teapotllm",
      dtype: "bnb4",
      architectures: ["T5ForConditionalGeneration"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Equal",
        "Expand",
        "Gather",
        "Greater",
        "If",
        "Less",
        "Log",
        "MatMul",
        "MatMulBnb4",
        "Min",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "ScatterND",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
