// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "wav2vec2-bert",
  models: [
    {
      model_id: "Xenova/w2v-bert-2.0",
      dtype: "quantized",
      architectures: ["Wav2Vec2BertModel"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "ConvInteger",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Einsum",
        "Gather",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pad",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/w2v-bert-2.0",
      dtype: "fp32",
      architectures: ["Wav2Vec2BertModel"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Einsum",
        "Gather",
        "MatMul",
        "Mul",
        "Pad",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/wav2vec2-bert-CV16-en",
      dtype: "quantized",
      architectures: ["Wav2Vec2BertForCTC"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "ConvInteger",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Einsum",
        "Gather",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pad",
        "Pow",
        "Range",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/wav2vec2-bert-CV16-en",
      dtype: "fp32",
      architectures: ["Wav2Vec2BertForCTC"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Einsum",
        "Gather",
        "MatMul",
        "Mul",
        "Pad",
        "Pow",
        "Range",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
  ],
};
