// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "xlm-roberta",
  models: [
    {
      model_id: "Snowflake/snowflake-arctic-embed-l-v2.0",
      dtype: "q4",
      architectures: ["XLMRobertaModel"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "CumSum",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Not",
        "Pow",
        "ReduceL2",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Snowflake/snowflake-arctic-embed-l-v2.0",
      dtype: "bnb4",
      architectures: ["XLMRobertaModel"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "CumSum",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "Not",
        "Pow",
        "ReduceL2",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Snowflake/snowflake-arctic-embed-l-v2.0",
      dtype: "quantized",
      architectures: ["XLMRobertaModel"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "CumSum",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Not",
        "Pow",
        "ReduceL2",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Snowflake/snowflake-arctic-embed-l-v2.0",
      dtype: "fp32",
      architectures: ["XLMRobertaModel"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "CumSum",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "Mul",
        "Not",
        "Pow",
        "ReduceL2",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/bge-m3",
      dtype: "fp32",
      architectures: ["XLMRobertaModel"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "Mul",
        "Not",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/bge-m3",
      dtype: "quantized",
      architectures: ["XLMRobertaModel"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Not",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/bge-reranker-base",
      dtype: "quantized",
      architectures: ["XLMRobertaForSequenceClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Not",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/bge-reranker-base",
      dtype: "fp32",
      architectures: ["XLMRobertaForSequenceClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Gemm",
        "MatMul",
        "Mul",
        "Not",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/paraphrase-multilingual-mpnet-base-v2",
      dtype: "quantized",
      architectures: ["XLMRobertaModel"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Not",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/paraphrase-multilingual-mpnet-base-v2",
      dtype: "fp32",
      architectures: ["XLMRobertaModel"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "CumSum",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "Mul",
        "Not",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "mixedbread-ai/deepset-mxbai-embed-de-large-v1",
      dtype: "q4",
      architectures: ["XLMRobertaModel"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "CumSum",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Not",
        "Pow",
        "ReduceL2",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "mixedbread-ai/deepset-mxbai-embed-de-large-v1",
      dtype: "bnb4",
      architectures: ["XLMRobertaModel"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "CumSum",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "Not",
        "Pow",
        "ReduceL2",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "mixedbread-ai/deepset-mxbai-embed-de-large-v1",
      dtype: "quantized",
      architectures: ["XLMRobertaModel"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "CumSum",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Not",
        "Pow",
        "ReduceL2",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "mixedbread-ai/deepset-mxbai-embed-de-large-v1",
      dtype: "fp32",
      architectures: ["XLMRobertaModel"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "CumSum",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "Mul",
        "Not",
        "Pow",
        "ReduceL2",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
