// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "yolov8",
  models: [
    {
      model_id: "Xenova/yolov8n-pose",
      dtype: "q4",
      architectures: [],
      ops: [
        "Add",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Gather",
        "MaxPool",
        "Mul",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sub",
        "Transpose",
      ],
    },
    {
      model_id: "Xenova/yolov8n-pose",
      dtype: "quantized",
      architectures: [],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConvInteger",
        "Div",
        "DynamicQuantizeLinear",
        "Gather",
        "MaxPool",
        "Mul",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sub",
        "Transpose",
      ],
    },
    {
      model_id: "Xenova/yolov8n-pose",
      dtype: "fp16",
      architectures: [],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Gather",
        "MaxPool",
        "Mul",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sub",
        "Transpose",
      ],
    },
  ],
};
