// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "yolos",
  models: [
    {
      model_id: "Oblix/yolov8x-doclaynet_ONNX",
      dtype: "quantized",
      architectures: [],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConvInteger",
        "Div",
        "DynamicQuantizeLinear",
        "Gather",
        "MaxPool",
        "Mul",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sub",
        "Transpose",
      ],
    },
    {
      model_id: "Oblix/yolov8x-doclaynet_ONNX",
      dtype: "fp32",
      architectures: [],
      ops: [
        "Add",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Gather",
        "MaxPool",
        "Mul",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sub",
        "Transpose",
      ],
    },
    {
      model_id: "Xenova/yolos-tiny",
      dtype: "quantized",
      architectures: ["YolosForObjectDetection"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "ConvInteger",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/yolos-tiny",
      dtype: "fp32",
      architectures: ["YolosForObjectDetection"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id:
        "onnx-internal-testing/tiny-random-YolosForObjectDetection-ONNX",
      dtype: "fp32",
      architectures: ["YolosForObjectDetection"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-YolosModel-ONNX",
      dtype: "fp32",
      architectures: ["YolosModel"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Resize",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
