export { default as AUDIO_CLASSIFICATION } from "./pipelines/audio-classification.js";
export { default as AUTOMATIC_SPEECH_RECOGNITION } from "./pipelines/automatic-speech-recognition.js";
export { default as DEPTH_ESTIMATION } from "./pipelines/depth-estimation.js";
export { default as DOCUMENT_QUESTION_ANSWERING } from "./pipelines/document-question-answering.js";
export { default as FEATURE_EXTRACTION } from "./pipelines/feature-extraction.js";
export { default as FILL_MASK } from "./pipelines/fill-mask.js";
export { default as IMAGE_CLASSIFICATION } from "./pipelines/image-classification.js";
export { default as IMAGE_FEATURE_EXTRACTION } from "./pipelines/image-feature-extraction.js";
// TODO: export { default as IMAGE_SEGMENTATION } from "./pipelines/image-segmentation.js";
export { default as IMAGE_TO_IMAGE } from "./pipelines/image-to-image.js";
export { default as IMAGE_TO_TEXT } from "./pipelines/image-to-text.js";
export { default as OBJECT_DETECTION } from "./pipelines/object-detection.js";
export { default as QUESTION_ANSWERING } from "./pipelines/question-answering.js";
export { default as SUMMARIZATION } from "./pipelines/summarization.js";
export { default as TEXT2TEXT_GENERATION } from "./pipelines/text2text-generation.js";
export { default as TEXT_CLASSIFICATION } from "./pipelines/text-classification.js";
export { default as TEXT_GENERATION } from "./pipelines/text-generation.js";
export { default as TEXT_TO_AUDIO } from "./pipelines/text-to-audio.js";
export { default as TOKEN_CLASSIFICATION } from "./pipelines/token-classification.js";
export { default as TRANSLATION } from "./pipelines/translation.js";
// TODO: export { default as ZERO_SHOT_CLASSIFICATION } from "./pipelines/zero-shot-classification.js";
export { default as ZERO_SHOT_AUDIO_CLASSIFICATION } from "./pipelines/zero-shot-audio-classification.js";
export { default as ZERO_SHOT_IMAGE_CLASSIFICATION } from "./pipelines/zero-shot-image-classification.js";
export { default as ZERO_SHOT_OBJECT_DETECTION } from "./pipelines/zero-shot-object-detection.js";
